### ISSUE TITLE
How to increase the number of simulated users

### ISSUE THREAD

**Issue by willann** [aligungr/UERANSIM#101]
hi！
I use the latest branch，successfully connected a user. How to modify the ue.yaml file,more users access in one event
thank you

**Comment by aligungr** [comment]
Hi @willann

Multiple UE and RAN feature (as well as load testing) is currently under development. However if you want to pre-access this feature, just check the `LoadTest.java` file. You can directly run the main method of `tr.havelsan.ueransim.LoadTest` class.

Also don't forget to check `app.log` and `loadtest.log` files with `tail -f` command.

**Comment by willann** [comment]
@aligungr OK, Thank you.

**Comment by aligungr** [comment]
@willann The feature is ready now. You can normally use ./run.sh in order to start the application. You can edit the `number-of-UE` parameter in `config/testing.yaml` in order to increase the number of UE.
