### ISSUE TITLE
issue about connect to free5GC

### ISSUE THREAD

**Issue by adamymlee** [aligungr/UERANSIM#124]
Hi UERANSIM team,
We met a problem when we use the config "free5gc"
Have you met the problem about the below error?

time="2020-09-02T11:34:51+08:00" level=info msg="supi conversion => imsi-002089300007487\n" func=free5gc/src/udm/producer.HandleGenerateAuthData file="/home/daily/free5gc/src/udm/producer/generate_auth_data.go:35" UDM=UEAU
time="2020-09-02T11:34:51+08:00" level=error msg="Return from UDR QueryAuthSubsData error" func=free5gc/src/udm/producer.HandleGenerateAuthData file="/home/daily/free5gc/src/udm/producer/generate_auth_data.go:40" UDM=UEAU
time="2020-09-02T11:34:51+08:00" level=info msg="403 Forbidden" func=free5gc/src/ausf/producer.UeAuthPostRequestProcedure file="/home/daily/free5gc/src/ausf/producer/ue_authentication.go:110" AUSF=UeAuthPost

Thanks.

**Comment by aligungr** [comment]
Hi @adamymlee 

I am not sure since it is free5gc related problem. But I think you may have forgotten to register UE on free5gc side using free5gc's webconsole.

Also see here: https://github.com/aligungr/UERANSIM/issues/71#issuecomment-666942646

**Comment by adamymlee** [comment]
How to register UE on free5gc side using free5gc's webconsole?
I cant find the related command on free5gc's github.

**Comment by s5uishida** [comment]
Hi @adamymlee 

Isn't [this](https://github.com/free5gc/free5gc/wiki/Appendix)?
