### ISSUE TITLE
The specific purpose of UERANSIM

### ISSUE THREAD

**Issue by myonlystarWang** [aligungr/UERANSIM#140]
Hi,
     I want to know the specific purpose of UERANSIM.
     As I know,this simulator can register to open5gs and establish pdu session by execute run.sh then select 4.
     But can the mechine which deploy UERANSIM ping the open5gs ogstun interface after pdu session established?

**Comment by s5uishida** [comment]
Probably I think and have high expectations that it will be possible if GTP-U support is added.

Sorry if I misunderstand.

**Comment by myonlystarWang** [comment]
> Probably I think and have high expectations that it will be possible if GTP-U support is added.
> 
> Sorry if I misunderstand.
@s5uishida 
Hi,
    What you said means UERANSIM have not supported U-plane，right?
BR,
wang

**Comment by s5uishida** [comment]
> What you said means UERANSIM have not supported U-plane，right?

I think it's under development. Right? @aligungr

**Comment by aligungr** [comment]
UERANSIM is a 5G UE and RAN simulator, our ultimate goal is to implement a complete UE and RAN (gNB). Which can be used as a simulator or real UE/gNB. But currently we provide some test cases such as initial-registration, pdu-session-establishment etc. People generally use UERANSIM to test their core network. However you can use this simulator for any "purpose".

---

Currently we don't support user plane functionalities. But you can manually use N3 interface to send and receive GTP-U packets after some PDU session establishment. Some people notified me that they successfully ping free5gc over GTP interface after PDU session establishment by UERANSIM. But we currently don't provide some builtin tool to utilize user plane. You should use the interface by yourself.

However as @s5uishida stated, user plane functions are in development now. After completion of that, you will be able to ping ogstun (or upftun0 etc.) device from inside of UERANSIM. And not just pinging, the UE will be able to access external internet through GTP-U interface as well.

**Comment by myonlystarWang** [comment]
Hi @aligungr ,
       I'm very glad to hear that the U-plane development is in the plan.
       

> But we currently don't provide some builtin tool to utilize user plane. You should use the interface by yourself.

So I can understand that the UE IP which was allocate by 5GC is already configured to the linux system when UERANSIM complete the registration process,right?
And if I want test UE ping 5GC or Internet,I should develop the GTP sender by myself just at this point?

BR,
Wang

**Comment by aligungr** [comment]
@myonlystarWang GTP-U is used in N3 interface between gNB and UPF, and yes normally you should be able to use N3 interface manually by behaving like gNB. But please make sure that core network (OPEN5GS, free5gc etc.) is built/configured/run correctly.

**Comment by myonlystarWang** [comment]
Hi aligungr,
      It is clear after your patiently explaination, thanks a lot for it.

BR,
Wang
