### ISSUE TITLE
AMF configuration update support

### ISSUE THREAD

**Issue by stan29-0R** [aligungr/UERANSIM#141]
Hello,
I would like to know if the messages "AMF configuration update support" received after the "NGSetupResponse" are supported (if the UERANSIM is able to Acknowledge such kind of message)?
BR

**Comment by aligungr** [comment]
Hello @stan29-0R currently we don't support AMF configuration update, but it is in the roadmap.

**Comment by stan29-0R** [comment]
###

**Comment by stan29-0R** [comment]
OK Thanks fo your feedback
