### ISSUE TITLE
Establishing GTP Tunnels

### ISSUE THREAD

**Issue by asoltanian1979** [aligungr/UERANSIM#171]
Hi 
I am studying 5GC. In the documents it was mentioned there is a GTP tunnel between gNodeB and AMF and there is a GTP tunnel between UE and UPF. as I checked in Wireshark , there is no GTP tunnel between UERANSIM and 5GC(I am using open5GS)
I wonder how do I configure these tunnels in practice...
Would you please help me out?
Thank you

**Comment by aligungr** [comment]
Hi Sultan

GTP tunnel is used for user plane data flow. We did not implement this feature yet, although it is very close to end. (That's the actual reason you could not see GTP packets in Wireshark.)

(Also GTP is used between gNB and UPF only. AMF and UE is not involved.)

**Comment by asoltanian1979** [comment]
Hi Ali
Thank you for this clarification. This saved me time. I hope We can see this feature soon

**Comment by aligungr** [comment]
@asoltanian1979 Now you should be able to see GTP packets with the latest version of UERANSIM.

After successful establishment of PDU Session, UE automatically sends ping request to google.com. see testing.yaml for more details.

**Comment by asoltanian1979** [comment]
Thank you for the update. I will check this....
