### ISSUE TITLE
Connection to AMF times out (open5gs)

### ISSUE THREAD

**Issue by Lozik** [aligungr/UERANSIM#172]
Hi,

I'm trying to connect UERANSIM to open5gs and I'm having some trouble with the gNB-AMF/N2 connection.
The connection cannot be constructed and the run-script then times out. I can affirm that the IP address and port number is correct and the packets arrive on the other side (using `tshark`). The request is a `INIT`, the AMF replies with a `INIT_ACK` but then UERANSIM (or the Ubuntu where it runs on) sends an `ABORT`. I've looked into the source code and it seems like the connection is handled by `com.sun.nio.sctp.SctpChannel`. I cannot find any documentation on why the Aborts are sent.

Does anyone know why an ABORT could be sent over SCTP before even a successfull connection? If I change the port of the AMF in UERANSIM without changing the actual port in open5gs, no `INIT_ACK` is sent, but a `ABORT` is replied (by the AMF-host). The ports and the AMF must thus be correctly set up. The AMF does not even show a log entry at all (which is strange).

Did anyone have similar issues? Is this maybe even a bug in one of the systems?

Thanks a lot!

**Comment by aligungr** [comment]
Hi Lozik, could you attach a .pcap file with INIT and ABORT messages included, and also output of `ifconfig` command on your system.

**Comment by s5uishida** [comment]
Hi @Lozik 

Here, it works fine with the following settings.

**1. Open5GS and UERANSIM IP addresses (VMs (Ubuntu 18.04) are VirtualBox)**

- Open5GS v2.0.20-7-g2d3b8ee - `192.168.100.30/20`
- UERANSIM 369808a version - `192.168.100.29/20`

**2. Changes from the default in the Open5GS configuration files**
`[open5gs/install/etc/open5gs]`
- `amf.yaml`
```
# diff -u amf.yaml.orig amf.yaml
--- amf.yaml.orig       2020-11-05 00:13:41.352457461 +0000
+++ amf.yaml    2020-10-08 05:42:47.215077761 +0000
@@ -165,7 +165,7 @@
       - addr: 127.0.0.5
         port: 7777
     ngap:
-      - addr: 127.0.0.5
+      - addr: 192.168.100.30
     guami:
       - plmn_id:
           mcc: 901
@@ -184,6 +184,7 @@
           mnc: 70
         s_nssai:
           - sst: 1
+            sd: 010203
     security:
         integrity_order : [ NIA2, NIA1, NIA0 ]
         ciphering_order : [ NEA0, NEA1, NEA2 ]
```
- `upf.yaml`
```
# diff -u upf.yaml.orig upf.yaml
--- upf.yaml.orig       2020-11-05 00:13:41.372289309 +0000
+++ upf.yaml    2020-11-05 00:38:50.052128811 +0000
@@ -165,7 +165,7 @@
     pfcp:
       - addr: 127.0.0.7
     gtpu:
-      - addr: 127.0.0.7
+      - addr: 192.168.100.30
     pdn:
       - addr: 10.45.0.1/16
       - addr: cafe::1/64
```
**3. I ran Open5GS as follows.**
```
./install/bin/open5gs-nrfd &
sleep 5
./install/bin/open5gs-smfd &
./install/bin/open5gs-amfd &
./install/bin/open5gs-upfd &
./install/bin/open5gs-ausfd &
./install/bin/open5gs-udmd &
./install/bin/open5gs-udrd &
```
**4. Changes from the default in the UERANSIM configuration files**
`[UERANSIM/config/open5gs]`
- `gnb.yaml`
```
$ diff -u gnb.yaml.orig gnb.yaml
--- gnb.yaml.orig       2020-11-05 01:55:25.812012513 +0000
+++ gnb.yaml    2020-11-05 01:57:12.279770416 +0000
@@ -2,7 +2,7 @@
 tac: 1
 nci: '000000000000000000000000000000010000'
 
-host: 127.0.0.1
+host: 192.168.100.29
 gtpPort: 2152
 tunPort: 49972
 
@@ -20,7 +20,7 @@
         hex: '5580'
       amfPointer:
         hex: 'a8'
-    host: 127.0.0.5
+    host: 192.168.100.30
     port: 38412
 
 supportedTAs:
@@ -37,4 +37,4 @@
               value:
                 hex: '010203'
 
-ignoreStreamIds: true
\ No newline at end of file
+ignoreStreamIds: true
```
**5. I was able to execute `4) pdu-session-establishment` normally.**
`[UERANSIM/logs]`
- `global.log`
```
[2020-11-05 01:57:39.933] [INFO] [CONNECTION] [gnb-1] Trying to establish SCTP connection... (192.168.100.30:38412)
[2020-11-05 01:57:39.945] [INFO] [CONNECTION] [gnb-1] SCTP connection established
[2020-11-05 01:57:40.974] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] NGSetup procedure is successful
[2020-11-05 01:57:43.385] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] Registration is successful
[2020-11-05 01:57:43.888] [INFO] [SYSTEM] Waiting for user-defined sleep (15 s)
[2020-11-05 01:57:57.973] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] PDU Session Establishment is successful
[2020-11-05 01:57:58.005] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] PDU Session Establishment is successful
```

**Comment by Lozik** [comment]
Hi @aligungr and @s5uishida 

Thanks a lot for your help. Having example config changes helped a lot! Effectively, I didn't change the 127.0.0.1 IP address because I thought it would be used for the gnb-ue connection (internally) but it makes sense that it has to be changed to the external address (and that the tool doesn't get the response). This might actually also help others.

Thanks again and sorry for any inconvenience caused!
