### ISSUE TITLE
initial registration failed between open5gs and UERANSIM 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#175]
hello experts i am using open5gs as core and UERANSIM as gnb . i want to connect  my UE with UERAN gnb. i gave my subscription information in ue.yaml but it says authenication failed. can you tell me the procedure how to latch my ue with gnb

**Comment by aligungr** [comment]
Hello @mimo123-code. Even tough UERANSIM provides both UE and GNB, our UE can connect only our GNB and vice versa. Connecting to external UE or GNBs is currently in roadmap.

**Comment by mimo123-code** [comment]
so i should keep the default configuration of the file only right?

**Comment by mimo123-code** [comment]
![Screenshot from 2020-11-07 22-30-14](https://user-images.githubusercontent.com/69619527/98447191-db90e480-2148-11eb-8802-c949565cc017.png)
i am using the default configuartion but still giving the same error

**Comment by aligungr** [comment]
Please make sure that you registered the UE in core network side (Open5GS using web-ui in your case).

Also we have a new commit on master branch. You can pull or re-clone in order to see registration reject cause.

**Comment by mimo123-code** [comment]
I have registered the ue information in webui also still the same error

**Comment by aligungr** [comment]
OK, now you should be able to see 5GMM Cause value after pulling on master branch. It may be useful to know what kind of MMCause value do you receive.
