### ISSUE TITLE
ping time out 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#180]
previously i was able to ping the google but now suddenly i am getting the error  [ERROR] [UE_APP] [ue-imsi-901700000000003] Ping timeout for google.com (172.217.163.142) after 3 sec no response. plzz help

**Comment by aligungr** [comment]
@mimo123-code Please make sure that you have successfully configured core network side and review core network documentation (Open5GS, free5gc etc.), especially IP routing and forwarding part.

I suspect the following:
IP routing/forwarding settings are not preserved after restarting your Linux computer. As you said you were able to ping google before, please double check if this is the case.

**Comment by mimo123-code** [comment]
thankyou it  worked
