### ISSUE TITLE
PDU Session Establishment is successful, but ping time out

### ISSUE THREAD

**Issue by dongzx666** [aligungr/UERANSIM#191]
I deployed open5gs on one virtual machine and ueransim on another. And I successfully established PDU connection, getting the error [ERROR] [UE_APP] [ue-imsi-901700000000003] Ping timeout for baidu.com (172.16.177.139) after 3 sec no response. Here is the log
```
@ubuntu:~/UERANSIM$ sh ./run.sh
INFO: Selected profile: "open5gs"
2020-11-24 02:36:26.704 [INFO] [CONN] [air] TUN Bridge has been started.
2020-11-24 02:36:26.722 [INFO] [CONN] [gnb-1] Trying to establish SCTP connection... (172.16.177.139:38412)
2020-11-24 02:36:26.741 [INFO] [CONN] [gnb-1] SCTP connection established
2020-11-24 02:36:26.747 [INFO] [PROC] [gnb-1] NGSetup procedure is starting
2020-11-24 02:36:26.865 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__PLMN_SEARCH
2020-11-24 02:36:27.433 [SUCC] [PROC] [gnb-1] NGSetup procedure is successful
2020-11-24 02:36:27.872 [INFO] [FLOW] [ue-901700000000003] UE connected to gNB.
2020-11-24 02:36:27.875 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__NORMAL_SERVICE
2020-11-24 02:36:27.970 [SUCC] [SYS] All UE and gNBs are initialized.
-----------------------------------------------------------------------------
List of pre-defined procedure tests:
1) initial-registration
2) periodic-registration
3) de-registration
4) pdu-session-establishment
Selection: 
4
2020-11-24 02:36:30.504 [INFO] [SYS] Starting predefined procedure test: "pdu-session-establishment"
2020-11-24 02:36:30.511 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_REGISTERED_INITIATED/MM_REGISTERED_INITIATED__NA
2020-11-24 02:36:31.452 [INFO] [STATE] [ue-901700000000003] UE switches to state: RM_REGISTERED
2020-11-24 02:36:31.453 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_REGISTERED/MM_REGISTERED__NORMAL_SERVICE
2020-11-24 02:36:31.454 [SUCC] [PROC] [ue-901700000000003] Registration is successful
2020-11-24 02:36:31.680 [SUCC] [PROC] [gnb-1] PDU Session Establishment is successful
2020-11-24 02:36:31.687 [INFO] [UEAPP] [ue-901700000000003] IPv4 connection setup with local IP: 10.45.0.4
2020-11-24 02:36:31.687 [INFO] [TUN] [air] IPv4 PDU session established (ue-901700000000003, 10.45.0.4)
2020-11-24 02:36:31.699 [INFO] [FLOW] [ue-901700000000003] PDU session established: PDU session identity value 1
2020-11-24 02:36:31.702 [SUCC] [PROC] [ue-901700000000003] PDU Session Establishment is successful
2020-11-24 02:36:41.806 [ERRO] [UEAPP] [ue-901700000000003] Ping timeout for www.baidu.com (103.235.46.39) after 10 sec no response
2020-11-24 02:36:47.898 [INFO] [TIMER] [ue-901700000000003] NAS Timer expired: NasTimer{timerCode=3510}
```
And here is the ip information
```
ubuntu:~/UERANSIM/build$ ip addr show
3: uesimtun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 500
    link/none 
    inet 10.45.0.2/32 scope global uesimtun
       valid_lft forever preferred_lft forever
    inet 10.45.0.3/32 scope global uesimtun
       valid_lft forever preferred_lft forever
    inet 10.45.0.4/32 scope global uesimtun
       valid_lft forever preferred_lft forever
    inet6 fe80::33b1:59f1:e80c:befa/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever

```
When I try to use the Tun function, ueransim issues a warning, here is the log
```
2020-11-24 02:52:09.030 [WARN] [TUN] [air] Tun bridge routing failed, target not found for: 10.45.0.2
```
```
@ubuntu:~/UERANSIM/build$ ping www.baidu.com -I 10.45.0.2
PING www.wshifen.com (104.193.88.77) from 10.45.0.2 : 56(84) bytes of data.
^C
--- www.wshifen.com ping statistics ---
169 packets transmitted, 0 received, 100% packet loss, time 172064ms
```
After checking issue 180, there is still no solution, so what's wrong with me？Thank you.

**Comment by aligungr** [comment]
Hello @dongzx666

Thanks for the detailed description.
There are two different issues here, and they are independent of each other.

---

First one.

If you successfully established a PDU session but the ping request timed out, then almost always there is a core network related problem. And since we know that Open5GS is well tested with UERANSIM, the only option is that there is a configuration issue.
Therefore make sure that you successfully configured the Open5GS side. Especially `ogstun` interface and UPF IP address. (I personally suspect the UPF address more in your case.)

---

Secondy.

The warning `Tun bridge routing failed, target not found for: 10.45.0.2` is a simple issue. According to your logs, UE's assigned IP address is `10.45.0.4`, but not `10.45.0.2`. Therefore UERANSIM's gNB unable to route IP packet from `10.45.0.2` since it is the incorrect IP address.

---

I hope it helps you and the others.

**Comment by dongzx666** [comment]
@aligungr Thank you for your quick reply.
To solve problem one, I reconfigured the IP address in `/etc/open5gs/upf.yaml`
```
upf:
    pfcp:
      - addr: 127.0.0.7
    gtpu:
     #  - addr: 127.0.0.7
     - addr: 172.16.177.139
    pdn:
      - addr: 10.45.0.1/16
      - addr: cafe::1/64
```
Then `sudo systemctl restart open5gs-upfd`, but the ping timeout still occurred... Sorry to trouble you again.

**Comment by aligungr** [comment]
@dongzx666  No worries. Could you share 2 pcap files (one for UERANSIM's machine, one for Open5GS's machine). In this way we can easily catch the problem.

**Comment by dongzx666** [comment]
@aligungr Due to the time difference, I come late. Here are three PCAP file links. 
Open5gs and UERANSIM are deployed on different virtual machines. During the deployment, only pdu-session-establishment is conducted, and there are no other network activities.
[open5gs-ens33](https://drive.google.com/file/d/1GI3F4fCcCp5myny3EIp3LSUG6Q4Dmo5s/view?usp=sharing)
[open5gs-ogstun](https://drive.google.com/file/d/18EaPMEquxT2e7fWWvWkEJRseDXRUEskC/view?usp=sharing)
[UERANSIM-ens33](https://drive.google.com/file/d/1MsFvdOZwhIagJ2D08I2u_d0ZHPDfg_PE/view?usp=sharing)

**Comment by aligungr** [comment]
@dongzx666 According to PCAP files, we can say that there is a NAT related problem. Does the following commands work for you?

```
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -I INPUT --source 10.45.0.2/16 -j ACCEPT
sudo iptables -t nat -I POSTROUTING --out-interface enp0s3 -j MASQUERADE
sudo iptables -I FORWARD --in-interface enp0s3 --out-interface ogstun -j ACCEPT
sudo iptables -I FORWARD --in-interface ogstun --out-interface enp0s3 -j ACCEPT
```

You may need to replace enp0s3 with your own if name.

**Comment by dongzx666** [comment]
After running the command you said on the virtual machine where open5gs is deployed, Ping is normal and Tun interface function is normal. 
Thank you very much. At the same time, I hope it can be helpful to other users.
**If the virtual machine deployed with open5gs is restarted, the above command needs to be rerun**
I noticed that the IP address of UE is randomly assigned. What is the impact of this? Or will the specified IP be supported in the future? 
Thank you very much.

**Comment by aligungr** [comment]
Thats great, and for the question;

Actually UE IP address is assigned by the core network (Open5GS etc). UE and gNB does not involved into this. So I cannot talk on behalf of core network in this case.

**Comment by Sabbir89** [comment]
Hi,
I have setup open5gs (4G EPC) on Ubuntu Instance in Openstack. Everthing is working fine except UE (Huawei Mate 20) has no internet connectivity. Even, it shows the network (4G) signal in the phone. When ping from the phone, it shows "Request timed out". 

**ubuntu@epc:~$** sudo iptables -L
Chain INPUT (policy ACCEPT)
target prot opt source destination
ACCEPT all -- 10.45.0.0/16 anywhere

Chain FORWARD (policy ACCEPT)
target prot opt source destination
ACCEPT all -- anywhere anywhere
ACCEPT all -- anywhere anywhere

Chain OUTPUT (policy ACCEPT)
target prot opt source destination

**ubuntu@epc:~$** sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target prot opt source destination

Chain INPUT (policy ACCEPT)
target prot opt source destination

Chain OUTPUT (policy ACCEPT)
target prot opt source destination

Chain POSTROUTING (policy ACCEPT)
target prot opt source destination
MASQUERADE all -- anywhere anywhere

**ubuntu@epc:~$** sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s 10.45.0.0/16 -j ACCEPT
-A FORWARD -i ogstun -o ens3 -j ACCEPT
-A FORWARD -i ens3 -o ogstun -j ACCEPT

**ubuntu@epc:~$** sudo iptables -S -t nat
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-A POSTROUTING -o ens3 -j MASQUERADE

ubuntu@epc:~$ sudo sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1

**Comment by evelbodevil** [comment]
@Sabbir89 did you work this out?

**Comment by Sabbir89** [comment]
@evelbodevil ,

Sorry for late response but I was just away from that part. Any suggestion?
Thanks a lot.

Sabbir

**Comment by Sabbir89** [comment]
> @dongzx666 According to PCAP files, we can say that there is a NAT related problem. Does the following commands work for you?
> 
> ```
> sudo sysctl -w net.ipv4.ip_forward=1
> sudo iptables -I INPUT --source 10.45.0.2/16 -j ACCEPT
> sudo iptables -t nat -I POSTROUTING --out-interface enp0s3 -j MASQUERADE
> sudo iptables -I FORWARD --in-interface enp0s3 --out-interface ogstun -j ACCEPT
> sudo iptables -I FORWARD --in-interface ogstun --out-interface enp0s3 -j ACCEPT
> ```
> 
> You may need to replace enp0s3 with your own if name.

@aligungr , I have setup UERANSIM and Open5GS and was having trouble with pinging Google. But, with these commands, it worked out. A lot of thanks for this effective idea. BTW, why we provide 10.45.0.2 while the assigned IP is .5?

Again thanks a million :)

BR,
Sabbir Ahmed

**Comment by aligungr** [comment]
@Sabbir89 You're welcome, brother.


> BTW, why we provide 10.45.0.2 while the assigned IP is .5?

Actually that was a typing error. The last number is always ignored because of the "`/16`" mask. Therefore .2, .3, .5, ... they are all the same. You can just use `10.45.0.0/16`

**Comment by Sabbir89** [comment]
Got it completely. Now, will try to make the connection in Openstack environment as well. 

Thank you so much, brother.

**Comment by talentueuxxav98** [comment]
> J’ai déployé open5gs sur une machine virtuelle et ueransim sur une autre. Et j’ai réussi à établir la connexion PDU, obtenant l’erreur [ERROR] [UE_APP] [ue-imsi-90170000000000003] Délai d’expiration du ping pour baidu.com (172.16.177.139) après 3 secondes sans réponse. Voici le journal
> 
> ```
> @ubuntu:~/UERANSIM$ sh ./run.sh
> INFO: Selected profile: "open5gs"
> 2020-11-24 02:36:26.704 [INFO] [CONN] [air] TUN Bridge has been started.
> 2020-11-24 02:36:26.722 [INFO] [CONN] [gnb-1] Trying to establish SCTP connection... (172.16.177.139:38412)
> 2020-11-24 02:36:26.741 [INFO] [CONN] [gnb-1] SCTP connection established
> 2020-11-24 02:36:26.747 [INFO] [PROC] [gnb-1] NGSetup procedure is starting
> 2020-11-24 02:36:26.865 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__PLMN_SEARCH
> 2020-11-24 02:36:27.433 [SUCC] [PROC] [gnb-1] NGSetup procedure is successful
> 2020-11-24 02:36:27.872 [INFO] [FLOW] [ue-901700000000003] UE connected to gNB.
> 2020-11-24 02:36:27.875 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_DEREGISTERED/MM_DEREGISTERED__NORMAL_SERVICE
> 2020-11-24 02:36:27.970 [SUCC] [SYS] All UE and gNBs are initialized.
> -----------------------------------------------------------------------------
> List of pre-defined procedure tests:
> 1) initial-registration
> 2) periodic-registration
> 3) de-registration
> 4) pdu-session-establishment
> Selection: 
> 4
> 2020-11-24 02:36:30.504 [INFO] [SYS] Starting predefined procedure test: "pdu-session-establishment"
> 2020-11-24 02:36:30.511 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_REGISTERED_INITIATED/MM_REGISTERED_INITIATED__NA
> 2020-11-24 02:36:31.452 [INFO] [STATE] [ue-901700000000003] UE switches to state: RM_REGISTERED
> 2020-11-24 02:36:31.453 [INFO] [STATE] [ue-901700000000003] UE switches to state: MM_REGISTERED/MM_REGISTERED__NORMAL_SERVICE
> 2020-11-24 02:36:31.454 [SUCC] [PROC] [ue-901700000000003] Registration is successful
> 2020-11-24 02:36:31.680 [SUCC] [PROC] [gnb-1] PDU Session Establishment is successful
> 2020-11-24 02:36:31.687 [INFO] [UEAPP] [ue-901700000000003] IPv4 connection setup with local IP: 10.45.0.4
> 2020-11-24 02:36:31.687 [INFO] [TUN] [air] IPv4 PDU session established (ue-901700000000003, 10.45.0.4)
> 2020-11-24 02:36:31.699 [INFO] [FLOW] [ue-901700000000003] PDU session established: PDU session identity value 1
> 2020-11-24 02:36:31.702 [SUCC] [PROC] [ue-901700000000003] PDU Session Establishment is successful
> 2020-11-24 02:36:41.806 [ERRO] [UEAPP] [ue-901700000000003] Ping timeout for www.baidu.com (103.235.46.39) after 10 sec no response
> 2020-11-24 02:36:47.898 [INFO] [TIMER] [ue-901700000000003] NAS Timer expired: NasTimer{timerCode=3510}
> ```
> 
> Et voici les informations ip
> 
> ```
> ubuntu:~/UERANSIM/build$ ip addr show
> 3: uesimtun: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 500
>     link/none 
>     inet 10.45.0.2/32 scope global uesimtun
>        valid_lft forever preferred_lft forever
>     inet 10.45.0.3/32 scope global uesimtun
>        valid_lft forever preferred_lft forever
>     inet 10.45.0.4/32 scope global uesimtun
>        valid_lft forever preferred_lft forever
>     inet6 fe80::33b1:59f1:e80c:befa/64 scope link stable-privacy 
>        valid_lft forever preferred_lft forever
> ```
> 
> Lorsque j’essaie d’utiliser la fonction Tun, ueransim émet un avertissement, voici le journal
> 
> ```
> 2020-11-24 02:52:09.030 [WARN] [TUN] [air] Tun bridge routing failed, target not found for: 10.45.0.2
> ```
> 
> ```
> @ubuntu:~/UERANSIM/build$ ping www.baidu.com -I 10.45.0.2
> PING www.wshifen.com (104.193.88.77) from 10.45.0.2 : 56(84) bytes of data.
> ^C
> --- www.wshifen.com ping statistics ---
> 169 packets transmitted, 0 received, 100% packet loss, time 172064ms
> ```
> 
> Après avoir vérifié le problème 180, il n’y a toujours pas de solution, alors qu’est-ce qui ne va pas chez moi ?Merci.

pouvez vous m'aider svp j'ai le meme probleme
