### ISSUE TITLE
Multiple uesimtun?

### ISSUE THREAD

**Issue by s5uishida** [aligungr/UERANSIM#192]
Hi @aligungr 

I'm sorry if this question was the similar question as before.

Can multiple UERANSIMs run on the same machine? For example,  specifying `uesimtunX` etc.
Is only `uesimtun` available as the TUN interface?

Thank you very much in advance.

**Comment by aligungr** [comment]
Hi @s5uishida 

Multiple UERANSIMs can run on the same machine, but for only control plane features. Only one UERANSIM can work in terms of user plane features, because of two reasons:

1. Multiple `uesimtun` interfaces are not supported. Actually this is not a real problem. If the community asks this feature we can support multiple uesimtun interfaces.
2. Only one GTP-U node may exist in one IP address. Because GTP-U port is 2152 as specified by 3GPP. This can be considered challenging, because two different processes cannot listen the same port number.

If we overcome the second problem, first one won't be difficult.

**Comment by s5uishida** [comment]
Hi @aligungr 

OK. Thanks.

BTW, It's not 5GC, but I took a look at the combination of Open5GS EPC and OAI UE / RAN.

https://github.com/s5uishida/open5gs_epc_oai_sample_config

In the above example, when running OAI **UE x 5** and RAN on VM4 , GTP-U (`2152/udp`) was bind, but `oip1`-`oip5` were generated as the TUN interfaces.

I will take a little look about this method.

**Comment by aligungr** [comment]
@s5uishida At first I thought you were asking about multiple RANs on the same machine, sorry. But now as I understand, there is a single RAN, and multiple UEs in OAI case. We can definitely achieve this in UERANSIM as well, but not yet :D.

We need two features in UERANSIM to achive this:
1. Multiple TUN support
2. Complete separation of UE and RAN

Initially I was thinking that separation should be done after implementation of NR radio interface, but indeed there is no obstacle to doing this right now.

Now I prioritize this feature, hopefully we will implement it soon.

**Comment by s5uishida** [comment]
Hi @aligungr 

Yes, I think if I could use the following on the condition as suitable for the current UERANSIM.

- multiple RANs on the same machine

For OAI, I was able to configure the following on the same machine:

- 1 RAN & 5 UEs
- 1 GTP-U (2152/udp)
- 5 TUN interfaces

But, this case is that UE and RAN are separated.
I'm sorry to confuse you.

I'm not going to affect the priority of your work.
However, I would be very glad if you could deal with it.

For the time being, I will try to build the following configuration here. It may be a little tight because it is built with VirtualBox of Core-i3 :-)

Thank you very much!

![network-overview](https://user-images.githubusercontent.com/52230356/100293847-5ae73a80-2fc8-11eb-9cf6-225332a76cdd.png)

P.S.

Once Open5GS supports NSSF and PCF, I would like to see how to network slicing with SST and SD. In that case, I would like to add network slicing to the above configuration and try it.

**Comment by s5uishida** [comment]
I have confirmed the operation of the above configuration.
It's a different environment, so it's VirtualBox of Core-i5 instead of Core-i3.

**Comment by aligungr** [comment]
@s5uishida Okay, thanks
