### ISSUE TITLE
UEContextRequest wasn't included in IntialUEMessage

### ISSUE THREAD

**Issue by aweimeow** [aligungr/UERANSIM#194]
Linked issues: #160, free5gc/free5gc#142

I was using free5gc v3.0.4 and UERANSIM master branch recently, and I ran into the exactly same problem as @BraedenDiaz did, I checked this issue with the working pcap (testing with Spirent Landslide).

According to my guess, the issue comes with **UEContextRequest wasn't included in IntialUEMessage**, here is the comparison of "UERANSIM + free5gc (left)" and "Landslide + free5gc (right)".

In left side (UERANSIM + free5gc), `InitialUEMessage` didn't have `UEContextRequst`.

![image](https://user-images.githubusercontent.com/5120010/100301043-43ad4a80-2fd2-11eb-940b-f4ec64865c13.png)

Therefore, free5gc will not set an important attribute `uEContextRequest` as `true` to the `ranUe` and `amfUe` instance.

![image](https://user-images.githubusercontent.com/5120010/100301185-9a1a8900-2fd2-11eb-9322-c73a7fd646eb.png)

When the `ueContextRequest` was set to `true`, free5gc will send the `SendInitialContextSetupRequest` when RegistrationAccept. Otherwise, it only send the DownlinkNasTransport message.

![image](https://user-images.githubusercontent.com/5120010/100301425-11501d00-2fd3-11eb-9c78-bb60836e7ff4.png)

And here is the other important attribute called `SentInitialContextSetupRequest`, it will set to `true` when `InitialContextSetupRequest` was sent, this attribute was also determine whether free5gc sends `PDUSessionResourceSetupRequest` or `InitialContextSetupRequest`.

![image](https://user-images.githubusercontent.com/5120010/100301726-b9fe7c80-2fd3-11eb-895c-a217deff3920.png)

c.c. @aligungr @BraedenDiaz @free5gc-org

**Comment by aligungr** [comment]
@aweimeow Thanks for the description. Our gNB now sends UEContextRequest field. You can check the latest master.

**Comment by aweimeow** [comment]
@aligungr Wow, thanks so efficiently fix, I'll try it, and I'll post the update here.

**Comment by aweimeow** [comment]
I've tried the latest commit, it does include the UEContextRequest, here is the screenshot.

![image](https://user-images.githubusercontent.com/5120010/100317342-250d7a80-2ff7-11eb-9a73-bbcdd8d18c88.png)

However, the ping still not working, am I missing something?

![image](https://user-images.githubusercontent.com/5120010/100317382-39517780-2ff7-11eb-809f-42e2a7630419.png)

**Comment by aligungr** [comment]
Actually no additional configuration is needed for that specific ping request. It's generally a core network related problem. This issue describes your case: https://github.com/aligungr/UERANSIM/issues/191

**Comment by BraedenDiaz** [comment]
Hey @aligungr and @aweimeow, I was going through the free5gc forums and found someone who forked free5gc and fixed some of its issues and they got it working with an Amarisoft gNodeB and a Huawei P40 UE.

free5gc forum post:
https://forum.free5gc.org/t/running-free5gc-stage3-with-amarisoft-gnodeb-ue/532

free5gc fork:
https://github.com/ralfkundel/free5gc

So I decided to try his fork with UERANSIM and was able to successfully get a ping reponse from google:

![UERANSIM-free5gc-ping-response](https://user-images.githubusercontent.com/21210929/100494851-fda3d400-3102-11eb-89bd-8c5289901079.jpg)

I went further and went through the instructions to set up a tunnel interface on UERANSIM and using ue-binder got successful results as well:

![ue-binder](https://user-images.githubusercontent.com/21210929/100494859-2af08200-3103-11eb-8b78-037d93750bcf.jpg)

So you can try and use the provided fork until free5gc fixes the issues in their future release.

**Comment by aweimeow** [comment]
@BraedenDiaz Thanks for the information and glad you made it works! I tried the folk version of free5gc, but I found the UPF didn't make the SNAT for UE packet, so although the ping go through core network, but it uses UE private IP as the source IP, and I won't get the ICMP reply.

```
2020-11-30 15:08:12.848 [INFO] [SYS] Starting predefined procedure test: "pdu-session-establishment"
2020-11-30 15:08:12.854 [INFO] [STATE] [ue-466920100002587] UE switches to state: MM_REGISTERED_INITIATED/MM_REGISTERED_INITIATED__NA
2020-11-30 15:08:13.956 [INFO] [STATE] [ue-466920100002587] UE switches to state: RM_REGISTERED
2020-11-30 15:08:13.957 [INFO] [STATE] [ue-466920100002587] UE switches to state: MM_REGISTERED/MM_REGISTERED__NORMAL_SERVICE
2020-11-30 15:08:13.958 [SUCC] [PROC] [ue-466920100002587] Registration is successful
2020-11-30 15:08:14.376 [WARN] [FLOW] [ue-466920100002587] SM cause received in PduSessionEstablishmentAccept: PDU session type IPv4 only allowed
2020-11-30 15:08:14.385 [INFO] [FLOW] [ue-466920100002587] PDU session established: PDU session identity value 1
2020-11-30 15:08:14.385 [INFO] [TUN] [air] IPv4 PDU session established (ue-466920100002587, 60.60.0.1)
2020-11-30 15:08:14.385 [INFO] [UEAPP] [ue-466920100002587] IPv4 connection setup with local IP: 60.60.0.1
2020-11-30 15:08:14.385 [SUCC] [PROC] [ue-466920100002587] PDU Session Establishment is successful
2020-11-30 15:08:14.386 [SUCC] [PROC] [gnb-1] PDU Session Establishment is successful
2020-11-30 15:08:18.401 [ERRO] [UEAPP] [ue-466920100002587] Ping timeout for google.com (172.217.160.78) after 3 sec no response
2020-11-30 15:08:25.851 [ERRO] [MSG] [gnb-1] Unhandled message received: NGAP_AMFStatusIndication
2020-11-30 15:08:29.118 [INFO] [TIMER] [ue-466920100002587] NAS Timer expired: NasTimer{timerCode=3510}
```

```
15:04:14.263342  In ethertype IPv4 (0x0800), length 100: (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto ICMP (1), length 84)
    60.60.0.1 > 172.217.160.110: ICMP echo request, id 1, seq 1, length 64
15:04:14.263361 Out 5e:90:8f:9f:ca:49 ethertype IPv4 (0x0800), length 100: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto ICMP (1), length 84)
    60.60.0.1 > 172.217.160.110: ICMP echo request, id 1, seq 1, length 64
```

**Comment by aweimeow** [comment]
Okay, I found the free5gc's UPF readme has the iptables rule that need to be configured. Issue solved.

**Comment by aweimeow** [comment]
@aligungr
