### ISSUE TITLE
v1.0.9 Java Exception During PDU Session Establishment

### ISSUE THREAD

**Issue by BraedenDiaz** [aligungr/UERANSIM#200]
Hey @aligungr I tried you're latest v1.0.9 release and got the following Java exception when trying to establish a PDU session:

![v1 0 9-Error](https://user-images.githubusercontent.com/21210929/100703153-31c80080-3360-11eb-8990-d4c2191a31b2.jpg)

I am still using free5gc and it seems to happen for each UE.

**Comment by s5uishida** [comment]
Hi @BraedenDiaz and @aligungr 

I think the following lines are missing when building.
```
--- makefile.orig       2020-12-01 06:39:22.850866790 +0000
+++ makefile    2020-12-01 07:01:06.301494602 +0000
@@ -23,6 +23,7 @@
        cp itms/target/itms-release.jar build/
        cp mts/target/mts-release.jar build/
        cp sctp/target/sctp-release.jar build/
+       cp rrc/target/rrc-release.jar build/
        cp misc/version build/
        @printf "${GREEN}UERANSIM successfully built.${NC}\n"

```

**Comment by aligungr** [comment]
@BraedenDiaz @s5uishida  Sorry I forgot that line. I just pushed the fix to master. You can pull again.
