### ISSUE TITLE
issue regarding TAC value

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#201]
hello when i changed the tac value on both open5gs and ueransim to 2 it gave me error NGSetup procedure is failed: unknown-PLMN
  .Is the ueransim is only compatible with only tac value of 1.?

**Comment by aligungr** [comment]
@mimo123-code That's core network configuration problem, but not UERANSIM.
You can use all TAC in UERANSIM side.

**Comment by mimo123-code** [comment]
@aligungr  previously when i connected open5gs with srsenb with a different tac value other than 1 it worked . but now with UERANSIM it is giving me error

**Comment by aligungr** [comment]
@mimo123-code Unfortunately I cannot know the problem in this case. But I still think that there is a configuration problem in core network side. Because srsenb is not **5G-SA** like UERANSIM. Maybe additional modifications are needed on core network side for 5G?
