### ISSUE TITLE
unable to find tracking area update request

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#203]
hello everybody when i attach my UERANSIM with open5gs i am unable to find initial attach message in wireshark where i can find the tracking area update request . can anyone help me regarding these

**Comment by aligungr** [comment]
Hello @mimo123-code If you mean initial AttachRequest message, then it is not used in 5G. It is a EPC message, therefore you cannot see it.

In 5G, we use RegistrationRequest instead of AttachRequest :D

**Comment by mimo123-code** [comment]
thanks @aligungr
