### ISSUE TITLE
support of multiple core netwrork 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#208]
hello i want to know whether the UERANSIM can be connected to multiple core network simultaneously. i want to perform the slicing of the network where each core networking serving differenet purpose

**Comment by aligungr** [comment]
@mimo123-code As far as I know, gNB can only connect to one core network by its nature, and so UERANSIM. But if you mean supporting multiple network slices for one core network, we didn't implement this feature yet, but it is on roadmap.

**Comment by mimo123-code** [comment]
Thanks @aligungr  .. I have one query sorry for bothering . Can you tell me any estimate till when the ue interface will be ready . Actually I need it for my thesis work ..

**Comment by aligungr** [comment]
@mimo123-code No problem. Most probably user interface will be ready in 2-3 weeks.

**Comment by mimo123-code** [comment]
That's great .Thanks @aligungr
