### ISSUE TITLE
TUN bridge error 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#210]
hello while using UE tun interface i am encountering the following error Tun bridge routing failed, target not found for: 10.45.0.2.  also my nas timer gets expired  after ping message anyone can help to how correct these error

**Comment by aligungr** [comment]
Make sure that you set the exact IP address given by core network. Most probability The IP address is different than 10.45.0.2.

**Comment by mimo123-code** [comment]
i couldnt find the ip that is assigned by the core network. do i need to use the ogustun interface ip which is given by the open5gs

**Comment by aligungr** [comment]
No, ogstun IP address is different from UE's IP.

Just check the UERANSIM terminal. Here's mine for example:

```
2020-12-10 10:32:08.591 [INFO] [UEAPP] [ue-901700000000003] IPv4 connection setup with local IP: 10.45.0.8
2020-12-10 10:32:08.591 [INFO] [TUN] [air] IPv4 PDU session established (ue-901700000000003, 10.45.0.8)
```

**Comment by mimo123-code** [comment]
ya got it .. thanks @aligungr . i have one query regarding 5G messages. in 5G identity request response and and request are exchanged between AMF and gnb but i cant see any of them . is it not implemented?

**Comment by aligungr** [comment]
We implemented the Identity Procedure in gNB side. But it is triggered by core network. If core network does not need an identity, it does not trigger this procedure. In other words it is optional and triggered by network.

**Comment by mimo123-code** [comment]
OK thanks for the info @aligungr
