### ISSUE TITLE
initial UE Message

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#212]
hello i have a query regarding the initial  registration message  which i got in the recent wireshark capture which is different from the usual wireshark capture . it consist of 5G-TMSI , UE Network capablity and lot of  other various capabilities are also exposed that  is never capture in before registration message there also i was able to capture service request and identity request which  was not captured before . what can be the reason for it.

**Comment by mimo123-code** [comment]
i got the answer actually it happens when the registration type is mobility updating but i dont know why the registration type switched to mobility updating . i didnt even changed the TAC value.

**Comment by rehmant16** [comment]
@mimo123-code Can you tell me how to make the registration type = "mobility update registration" if you were able to figure that out.

Thank You!
