### ISSUE TITLE
Registration failed: DNN not supported or not subscribed in the slice

### ISSUE THREAD

**Issue by user87654** [aligungr/UERANSIM#213]
I am getting the same errors as mentioned in this issue #199 when I try to register a UE using UE RANSIM and Open5GS. Does anyone knows how to resolve it?

```
[ERRO] [PROC] [ue-901700000000003] Registration failed: DNN not supported or not subscribed in the slice
[ERRO] [NIMPL] [ue-901700000000003] Registration rejected with unhandled MMCause: DNN not supported or not subscribed in the slice
```

**Comment by acetcom** [comment]
@user87654 Please share the pcap to find out why this error occurred.

**Comment by aligungr** [comment]
@user87654 Did you created the UE using Open5Gs web interface? The core network need to know subcriber info before registration procedure.

**Comment by user87654** [comment]
I did a fresh install of Open5GS, UERANSIM, and the nat rules and it worked. Thanks.
