### ISSUE TITLE
how to add  multiple UE in new configuration

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#215]
under upgrade 2.01 how to add multiple UE as testing.yaml has been removed

**Comment by aligungr** [comment]
Use:
```
./nr-cli ue-create -i 901700000000003
./nr-cli ue-create -i 901700000000004
./nr-cli ue-create -i 901700000000005
./nr-cli ue-create -i 901700000000006
...
```

`-i` option specifies the IMSI number. More info: `nr-cli ue-create --help`

**Comment by mimo123-code** [comment]
thanks @aligungr

**Comment by mimo123-code** [comment]
Hello @aligungr  in UERANSIM the UE doesn't send the mobility update even if I change the tracking area . Ivan you tell how to trigger the registration type mobility update

**Comment by aligungr** [comment]
@mimo123-code mobility update is not implemented yet

**Comment by mimo123-code** [comment]
but once i got registration type mobility updating . iam sharing the screenshot 
![Screenshot from 2020-12-14 16-02-54](https://user-images.githubusercontent.com/69619527/102071101-0811dd80-3e26-11eb-90d8-afc0182893b4.png)

**Comment by aligungr** [comment]
Interesting. Could you send the pcap file?

**Comment by mimo123-code** [comment]
the pcap file size is too huge . i also got ue radio capablity info indication,identity request and response

**Comment by mimo123-code** [comment]
hello @aligungr  can i send you the pcap file in your mail id

**Comment by aligungr** [comment]
Sure

**Comment by mimo123-code** [comment]
https://www.transfernow.net/y7jPrH122020
i have sent  the file . here is the link of the send file

**Comment by mimo123-code** [comment]
@aligungr i found something unsual in the pcap file . initial in the NG SETUP Request ran node name was UERANSIM/Gnb1 and at another NGsetup request RANnode name cahnged to 5G GNB-CU. how the ran node name is changing
