### ISSUE TITLE
[Question] master branch can't work with Free5GC (Registration Request issue)

### ISSUE THREAD

**Issue by aweimeow** [aligungr/UERANSIM#217]
Hello @aligungr, 

The cli function is awesome, I can write the customize testing script as need.
But I tried to run UERANSIM@master with free5GC@v3.0.4, it has some issue when sending UE RegistrationRequest.

The current version of UERANSIM sends the **RegistrationComplete** message to AMF, and as the following definition in 3GPP TS 24.502 4.2.2.2, if AMF receives the **RegistrationComplete** message, and PDUSessionList wasn't include in **RegistrationRequest**, AMF will send **UEContextReleaseCommand** to UE, so the connection breaks and UE can't establish the PDU session.

![image](https://user-images.githubusercontent.com/5120010/102294051-5b4d7280-3f83-11eb-9048-be3230c8f327.png)

Compare to the previous version of UERANSIM(7c89a4b3ffca018671c82e35f477faa260ff5414), it was able to work with free5GC, and its UE doesn't send **RegistrationComplete** message.

![image](https://user-images.githubusercontent.com/5120010/102294376-255cbe00-3f84-11eb-95df-8d23a4f2ce79.png)

Could you please help me to solve this issue?

Thanks.

**Comment by aligungr** [comment]
Hello @aweimeow 

Sorry I accidentally injected some bug in v2.0.1, and now I fixed the issue. You can pull the master.

Thanks for reporting the issue.

**Comment by aweimeow** [comment]
Hmm, it's not working yet. 

I'm looking for the problem, in the same time, I am just wondering why `PDU session establishment request` sends before UERANSIM gets `Registration Accept`?

![image](https://user-images.githubusercontent.com/5120010/102564904-5faa9480-4117-11eb-8ceb-2f0eed238243.png)

**Comment by aweimeow** [comment]
Oops, it works, maybe my custom testing script has some bugs.

**Comment by aligungr** [comment]
Since the CLI commands are unblocking, a sleep may be required between the commands depending on your script.

**Comment by aweimeow** [comment]
Thanks!
