### ISSUE TITLE
Cant build project. nr-build fails 

### ISSUE THREAD

**Issue by stelarsk** [aligungr/UERANSIM#221]
`./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_QosFlowSetupResponseListSURes.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_QosFlowSetupResponseItemSURes) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array)); 

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_QoSFlowsUsageReportList.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_QoSFlowsUsageReport_Item) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_QosFlowToBeForwardedList.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_QosFlowToBeForwardedItem) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_RATRestrictions.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_RATRestrictions_Item) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_ServiceAreaInformation.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_ServiceAreaInformation_Item) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_UEHistoryInformation.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_LastVisitedCellItem) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_TAIBroadcastEUTRA.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_TAIBroadcastEUTRA_Item) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \

./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)

./asn_generated/NGAP_TAIBroadcastNR.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_TAIBroadcastNR_Item) list;

./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_TAICancelledEUTRA.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_TAICancelledEUTRA_Item) list;
  ^
./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_TAICancelledNR.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_TAICancelledNR_Item) list;
  ^
./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_TAIListForWarning.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_TAI) list;
  ^
./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_XnExtTLAs.h:27:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(struct NGAP_XnExtTLA_Item) list;
  ^
./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_XnGTP-TLAs.h:25:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(NGAP_TransportLayerAddress_t) list;
  ^
./asn_generated/asn_SET_OF.h:14:22: error: ‘decltype’ has not been declared
         void (*free)(decltype(*array));  \
                      ^
./asn_generated/asn_SEQUENCE_OF.h:19:29: note: in expansion of macro ‘A_SET_OF’
 #define A_SEQUENCE_OF(type) A_SET_OF(type)
                             ^
./asn_generated/NGAP_XnTLAs.h:25:2: note: in expansion of macro ‘A_SEQUENCE_OF’
  A_SEQUENCE_OF(NGAP_TransportLayerAddress_t) list;
  ^
In file included from tr_havelsan_ueransim_NgapJni.cpp:6:0:
pdu_data.h:8:1: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum class PduType
 ^
tr_havelsan_ueransim_NgapJni.cpp:8:8: error: ‘constexpr’ does not name a type
 static constexpr int RESULT_OK = 0;
        ^
tr_havelsan_ueransim_NgapJni.cpp:8:8: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
tr_havelsan_ueransim_NgapJni.cpp:9:8: error: ‘constexpr’ does not name a type
 static constexpr int RESULT_DECODING_FAILED = 1;
        ^
tr_havelsan_ueransim_NgapJni.cpp:9:8: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
tr_havelsan_ueransim_NgapJni.cpp:10:8: error: ‘constexpr’ does not name a type
 static constexpr int RESULT_ENCODING_FAILED = 2;
        ^
tr_havelsan_ueransim_NgapJni.cpp:10:8: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
tr_havelsan_ueransim_NgapJni.cpp: In function ‘_jbyteArray* Java_tr_havelsan_ueransim_ngap0_NgapJni_convertEncoding(JNIEnv*, jclass, jbyteArray, jint, jint, jintArray, jint)’:
tr_havelsan_ueransim_NgapJni.cpp:14:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto pdu_type = static_cast<PduType>(pduType);
   ^
tr_havelsan_ueransim_NgapJni.cpp:14:8: error: ‘pdu_type’ does not name a type
   auto pdu_type = static_cast<PduType>(pduType);
        ^
tr_havelsan_ueransim_NgapJni.cpp:15:54: error: ‘pdu_type’ was not declared in this scope
   asn_TYPE_descriptor_t* desc = pdu_type_description(pdu_type);
                                                      ^
tr_havelsan_ueransim_NgapJni.cpp:18:52: error: ‘nullptr’ was not declared in this scope
   jbyte *buffer = pEnv->GetByteArrayElements(data, nullptr);
                                                    ^
tr_havelsan_ueransim_NgapJni.cpp:21:3: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
   auto pdu = calloc(1, pdu_size);
   ^
tr_havelsan_ueransim_NgapJni.cpp:21:8: error: ‘pdu’ does not name a type
   auto pdu = calloc(1, pdu_size);
        ^
tr_havelsan_ueransim_NgapJni.cpp:22:112: error: ‘pdu’ was not declared in this scope
   asn_dec_rval_t decode_res = asn_decode(NULL, static_cast<asn_transfer_syntax>(fromEncoding), desc, (void **)&pdu, buffer, buffer_size);
                                                                                                                ^
tr_havelsan_ueransim_NgapJni.cpp:25:26: error: ‘asn_dec_rval_code_e’ is not a class or namespace
   if (decode_res.code != asn_dec_rval_code_e::RC_OK)
                          ^
tr_havelsan_ueransim_NgapJni.cpp:28:18: error: ‘RESULT_DECODING_FAILED’ was not declared in this scope
     res_arr[0] = RESULT_DECODING_FAILED;
                  ^
tr_havelsan_ueransim_NgapJni.cpp:39:18: error: ‘RESULT_ENCODING_FAILED’ was not declared in this scope
     res_arr[0] = RESULT_ENCODING_FAILED;
                  ^
tr_havelsan_ueransim_NgapJni.cpp:16:10: warning: unused variable ‘pdu_size’ [-Wunused-variable]
   size_t pdu_size = pdu_type_size(pdu_type);
          ^
makefile:12: recipe for target 'libngap-basis.a' failed
make[1]: *** [libngap-basis.a] Error 1
make[1]: Leaving directory '/opt/ueransim/UERANSIM/native/ngap-native'
makefile:7: recipe for target 'build' failed
make: *** [build] Error 2
`
Envirionment:
Ubuntu 16.04
Java 11 open-jdk
maven 3.6.3

**Comment by aligungr** [comment]
Please run all commands in **Dependencies** section at https://github.com/aligungr/UERANSIM/wiki/Installation-and-Usage

The reason of this error is usage of an old version of g++.

**Comment by stelarsk** [comment]
> Please run all commands in **Dependencies** section at https://github.com/aligungr/UERANSIM/wiki/Installation-and-Usage
> 
> The reason of this error is usage of an old version of g++.

I have g++ v9. The wiki says  6.4.0 or later. I will try with the latest g++ release.
(g++-9 is already the newest version (9.3.0-10ubuntu2~16.04).)

**Comment by aligungr** [comment]
I pushed a hotfix. Please pull and try again using master branch.

**Comment by stelarsk** [comment]
> I pushed a hotfix. Please pull and try again using master branch.

Works. Awesome. Thanks for the hotfix and immediate reply.

![image](https://user-images.githubusercontent.com/53342620/102890608-04e9a380-445d-11eb-90af-bf4a9ee31aec.png)
