### ISSUE TITLE
support for SRS lte

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#223]
hello i want to know weather can UERANSIM can be connected to srslte core.

**Comment by aligungr** [comment]
Hello @mimo123-code. UERANSIM can only connect to 5G core network. LTE/4G core network is not (and will not be) supported.

**Comment by mimo123-code** [comment]
ok @aligungr  . If you dont mind can you tell any update on radio interface for UERANSIM. will it be ready in next 1 or 2 week . as you told before it will be ready by 2 or 3 weeks . sorry for bothering

**Comment by aligungr** [comment]
I thought you were asking user interface (UI) :D

Radio interface is in early stages yet. I think it'll take several months.

**Comment by mimo123-code** [comment]
Oho  :D .. initially I thought for user interface only .. later when I saw the route map of yours I thought radio interface is about to come . Can you tell me about the user interface only . That will also serve my purpose

**Comment by aligungr** [comment]
UI may come probably in a week or 2-weeks.
