### ISSUE TITLE
unable to establish pdu session 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#225]
hello I am facing a error when I run the command session establishment . it says Unhandled message received: Pdu SessionEstablishmentRequest. can you please tell me How to correct the error

**Comment by aligungr** [comment]
Please send a pcap file if you can

**Comment by mimo123-code** [comment]
i have resolved the issue @aligungr . i have one query can now multiple gnb is supported?

**Comment by mimo123-code** [comment]
[jpdu.zip](https://github.com/aligungr/UERANSIM/files/5759844/jpdu.zip)
here is the pcap file @aligungr

**Comment by aligungr** [comment]
Thanks @mimo123-code I'll check it

**Comment by mimo123-code** [comment]
sorry @aligungr   i forgot to update it i corrected the  error. It was problem on the core side
