### ISSUE TITLE
"An illegal reflective access operation has occurred" while I was running 'nr-build'. 

### ISSUE THREAD

**Issue by donganyuan** [aligungr/UERANSIM#227]
Hello, 
While I was tring to run 'nr-build', some error happened.

$ ./nr-build

mkdir -p build
rm -fr build/*
(cd native/ngap-native && make clean)
make[1]: Entering directory '/home/ubuntu/work_jftt/UERANSIM/native/ngap-native'
rm -f ./src/asn_generated/*.o
rm -f ./src/asn_generated/*.a
rm -f ./src/*.o
rm -f ./src/*.a
rm -f *.o *.so *.a
make[1]: Leaving directory '/home/ubuntu/work_jftt/UERANSIM/native/ngap-native'
(cd native/rrc-native && make clean)
make[1]: Entering directory '/home/ubuntu/work_jftt/UERANSIM/native/rrc-native'
rm -f ./src/asn_generated/*.o
rm -f ./src/asn_generated/*.a
rm -f ./src/*.o
rm -f ./src/*.a
rm -f *.o *.so *.a
make[1]: Leaving directory '/home/ubuntu/work_jftt/UERANSIM/native/rrc-native'
(cd native/crypto-native && make clean)
make[1]: Entering directory '/home/ubuntu/work_jftt/UERANSIM/native/crypto-native'
rm -f *.o *.so
make[1]: Leaving directory '/home/ubuntu/work_jftt/UERANSIM/native/crypto-native'
(cd native/app-native && make clean)
make[1]: Entering directory '/home/ubuntu/work_jftt/UERANSIM/native/app-native'
rm -f *.o *.so
make[1]: Leaving directory '/home/ubuntu/work_jftt/UERANSIM/native/app-native'
(cd native/uesimtun && make -f ue-binder.mk clean)
make[1]: Entering directory '/home/ubuntu/work_jftt/UERANSIM/native/uesimtun'
rm -f libue-binder.so
rm -f ./obj/ue-binder/*.o ./obj/ue-binder/*.so
make[1]: Leaving directory '/home/ubuntu/work_jftt/UERANSIM/native/uesimtun'
mvn -q clean
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: No address associated with hostname -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
makefile:31: recipe for target 'clean' failed
make: *** [clean] Error 1
ubuntu@ubuntu:~/work_jftt/UERANSIM$ ping www.baidu.com
ping: www.baidu.com: Temporary failure in name resolution

Let me know if I missed something
Greetings

**Comment by donganyuan** [comment]
Hello，
After I configure DNS, the error message changed. 
--------------------------------------------------------------------------
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: No address associated with hostname -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
makefile:31: recipe for target 'clean' failed
make: *** [clean] Error 1
-----------------------------------------------

Let me know if I missed something
Greetings

**Comment by aligungr** [comment]
@donganyuan 

I think there is a maven related problem in your system. Or maybe your computer is not connected to internet.

I think I cannot help you for this specific problem, sorry.

**Comment by donganyuan** [comment]
@aligungr 
Thank you very much !  
nr-build is OK now.   It's just a network problem. I have solved it already !
