### ISSUE TITLE
regarding UE interface

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#231]
Hello @aligungr  just wanted to know update on UE interface . Till when it will be released . Needed for the work purpose . Thanks in advance

**Comment by aligungr** [comment]
@mimo123-code UI is normally complete but not published yet. We're working on some official procedures with our company (Havelsan). Unfortunately I cannot give an exact date but hopefully in a few weeks.

**Comment by mimo123-code** [comment]
ok thanks @aligungr
