### ISSUE TITLE
[Question]How can I test the connectivity between UEs

### ISSUE THREAD

**Issue by dongzx666** [aligungr/UERANSIM#232]
[Background]
Open5gs is deployed on an Ubuntu server, UERANSIM is deployed on another server. And UE can successfully Ping Google.
[Situation]
Through the `nr-cli ue-ping <imsi> 10.45.0.30,` I used the IP of one UE(10.45.0.29) to Ping the IP of another UE(10.45.0.30), and it failed. The pcap file shows that this process has not been transferred, and Source is 10.45.0.29, Destination is 10.45.0.30.
[Question]
My ultimate ideal way is to connect the two UEs by VOIP. But the first step is to find out whether the two UEs can communicate with each other through 5GC. So do you have any suggestions? Thank you very much.

**Comment by aligungr** [comment]
@dongzx666 Can I ask the following 6 PCAP files to analyze the situation?

1) **UE1**'s machine **uesimtunX** interface
2) **UE1**'s machine **ethernet** interface
3) **UE2**'s machine **uesimtunX** interface
4) **UE2**'s machine **ethernet** interface
5) **Open5GS**' machine **ogstun** interface
6) **Open5GS**' machine **ethernet** interface

**Comment by dongzx666** [comment]
Oh, the two UEs I tested were created by the same UERANSIM. 
Here are the pcap files I shared.
[pcap.zip](https://github.com/aligungr/UERANSIM/files/5826123/pcap.zip)
The external ip of UERANSIM is 10.108.102.8(enp4s0), and the external ip of Open5GS is 10.108.99.170(eno1)
Thank you!

**Comment by aligungr** [comment]
@dongzx666 Thanks for the pcaps.

But, I think I could not find open5gs' machine's pcap. There is a free5gc pcap, but other pcaps seem to use open5gs instead of free5gc.

**Comment by dongzx666** [comment]
@aligungr 
In fact, I didn't run free5GC. It was Open5GS that I ran. The mode UERANSIM chose was Open5GS too. Could you let me know what makes you think that file is a free5gc pcap. The filename is **eno1-10.108.99.170.pcap**.
Thanks.

**Comment by s5uishida** [comment]
Hi @dongzx666 , @aligungr 

Here, ping is successful in each of the following cases `A <-> B` and `X <-> Y`.

For your reference.

```
case 1)

         Open5GS              UERANSIM
     ----------------     ----------------
VM0 | ogstun0        |   | uesimtun0      | VM1
    | 10.45.0.1      |---| 10.45.0.2 (A)  |
    |----------------|    ----------------
    |                |
    |----------------|    ----------------
    | ogstun2        |   | uesimtun0      | VM2
    | 10.46.0.1      |---| 10.46.0.2 (B)  |
     ----------------     ----------------
```

```
case 2)

         Open5GS              UERANSIM
     ----------------     ----------------
VM0 | ogstun0        |   | uesimtun0      | VM1
    | 10.45.0.1      |---| 10.45.0.2      |
    |----------------|   |----------------|
    |                |   |                |
    |----------------|   |----------------|
    |                |   | uesimtun1      |
    |                |---| 10.46.0.3 (X)  |
    | ogstun2        |    ----------------
    | 10.46.0.1      |
    |                |    ----------------
    |                |   | uesimtun0      | VM2
    |                |---| 10.46.0.2 (Y)  |
     ----------------     ----------------
```

**Comment by aligungr** [comment]
> Could you let me know what makes you think that file is a free5gc pcap.

@dongzx666 I think you uploaded the wrong zip file, here's the contents of the zip file I think, am I missing something :) ?

![image](https://user-images.githubusercontent.com/25206055/104889377-316edd80-597f-11eb-8410-5771e58a0787.png)

---
Thanks for the comment @s5uishida. Yes normally it should work without a problem.

**Comment by dongzx666** [comment]
@aligungr 
It's my fault. I did upload the wrong file. So sorry.
Here are re-uploaded pcap files [new-pcap.zip](https://github.com/aligungr/UERANSIM/files/5830762/new-pcap.zip)
Thanks!
- - -
@s5uishida Thank you for sharing two cases. But my case is not the above two. How should I deal with the following situation?
```
         Open5GS              UERANSIM
     ----------------     ----------------
VM0 |                |   | uesimtun0      | VM1
    |                |---| 10.45.0.2      |
    |                |   |----------------|
    |  ogstun        |   |                |
    |  10.45.0.1     |   |----------------|
    |                |   | uesimtun1      |
    |                |---| 10.46.0.3      |
     ----------------     ----------------
```
