### ISSUE TITLE
CMAKE error

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#240]
hello i am encountering these error 
rm -fr logs # Old version log files
mkdir -p build
rm -fr build/*
CMake Error: The source directory "/home/mimo/UERANSIM-3.0.1/cmake-build-release" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
makefile:5: recipe for target 'build' failed
make: *** [build] Error 1

I have installed cmake  also still encountering these error.

**Comment by j0lama** [comment]
Hi @mimo123-code,

I'm getting the same error. How did you fix it?

**Comment by mimo123-code** [comment]
update the cmake version to 3.7 or higher

**Comment by j0lama** [comment]
> update the cmake version to 3.7 or higher

I'm using cmake 3.10.2

**Comment by j0lama** [comment]
> > update the cmake version to 3.7 or higher
> 
> I'm using cmake 3.10.2

I managed to make it work with cmake 3.19.4. Thanks!

**Comment by cloudwiser** [comment]
I got this issue after snap installing the latest version of cmake...so I completely removed cmake via `sudo apt remove cmake `and `sudo snap remove cmake` and then did `snap install cmake --classic `once again. 
`make` then worked for me.

**Comment by holycz** [comment]
> I got this issue after snap installing the latest version of cmake...so I completely removed cmake via `sudo apt remove cmake `and `sudo snap remove cmake` and then did `snap install cmake --classic `once again. `make` then worked for me.

deal with   thank u
