### ISSUE TITLE
Unhandled message received: PduSessionEstablishmentRequest

### ISSUE THREAD

**Issue by PHXi** [aligungr/UERANSIM#247]
Hello @aligungr ,I read your article “5GC Advanced Example with UERANSIM” in OPEN5GS’ documentation.It’s really nice that I succeed to create pdu-session with ue0 and ping google with uesimtun0.

However,I fail to create pdu-session with ue1.yaml thought ue1 can regist successfully .Nr-agent shows  that :

Ue-901700000000004 Unhandled message received: PduSessionEstablishmentRequest

The smf.log in open5gs-c plane shows:
[smf] ERROR: [imsi-901700000000004:1] No dnnConfigurations (../src/smf/bums-handler.c:257)

There are my configurations:
5gc-c:
Ip:192.168.56.11
Smf.yaml:
smf:
    sbi:
      - addr: 127.0.0.4
        port: 7777
    gtpc:
      - addr: 127.0.0.4
      - addr: ::1
    pfcp:
      - addr: 192.168.56.11
      - addr: ::1
pdn:
      - addr: 10.45.0.1/16
        apn: internet
        dev: ogstun
      - addr: 10.46.0.1/16
        apn: internet2
        dev: ogstun2
      - addr: 10.47.0.1/16
        apn: ims
        dev: ogstun3
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    mtu: 1400
    freeDiameter: /etc/freeDiameter/smf.conf
/......./
    upf:
    pfcp:
      - addr: 192.168.56.9
        dnn: ims
      - addr: 192.168.56.8
        dnn: [internet, internet2]

5gc-u:
Ip:192.168.56.8
Upf.yaml:
/..../
upf:
    pfcp:
      - addr: 192.168.56.8
    gtpu:
      - addr: 192.168.56.8
    pdn:
      - addr: 10.45.0.1/16
        apn: internet
        dev: ogstun
      - addr: 10.46.0.1/16
        apn: internet2
        dev: ogstun2

Ue1.conf:

supi: 'imsi-901700000000004'

plmn:
  mcc: 901
  mnc: 70

key: '465B5CE8B199B49FAA5F0A2EE238A6BC'

op: 'E8ED289DEBA952E4283B54E88E6183CA'

amf: '8000'

imei: '356938035643803'

dnn: 'internet2'

requestedNssai:
  - sst:
      hex: '01'
    sd:
      hex: '010203'

I’ll appreciate it if you can figure it out.

**Comment by aligungr** [comment]
Hello @PHXi 

I think `No dnnConfigurations` implies there is a problem related to core network configurations. Make sure that the settings for the second UE in Open5gs web UI are correct. (Perhaps APN is missing)

Btw, I recommend you to use the latest version of UERANSIM

**Comment by PHXi** [comment]
Hi @aligungr,I changed the APN in WEB UI and it works.Thanks a lot!
