### ISSUE TITLE
Compilation errors and a possible patch on Ubuntu

### ISSUE THREAD

**Issue by strongcourage** [aligungr/UERANSIM#248]
Hi,

I try to compile the most recent version of UERANSIM `335da66` on Ubuntu 16.04 using g++ version 7.5 and cmake version 3.19.4. All dependencies have been installed. However, when I compiled it, I had the following error:
```
src/ue/tun/config.cpp:67:12: In function ‘int ExecOutput(const char*, std::__cxx11::string&)’:
.../src/ue/tun/config.cpp:67:12: error: lvalue required as unary ‘&’ operand
     return WEXITSTATUS(pclose(pipe));
```

After googling, I found a [simple solution](https://stackoverflow.com/questions/13674660/unix-c-portable-wexitstatus) to fix this error and build successfully. Here is the patch:
```
$ git diff src/ue/tun/config.cpp
diff --git a/src/ue/tun/config.cpp b/src/ue/tun/config.cpp
index 1d6cbbc..cfe514a 100644
--- a/src/ue/tun/config.cpp
+++ b/src/ue/tun/config.cpp
@@ -64,7 +64,8 @@ static int ExecOutput(const char *cmd, std::string &output)
         return -1;
     }
     output = result;
-    return WEXITSTATUS(pclose(pipe));
+    int status = pclose(pipe);
+    return WEXITSTATUS(status);
 }
```
Thank you. Best regards.

**Comment by aligungr** [comment]
Hi @strongcourage.

Thank you for the fix. I've just pushed it to the master.

**Comment by strongcourage** [comment]
Great! Thank you @aligungr.
