### ISSUE TITLE
 'mnc' is too small.

### ISSUE THREAD

**Issue by willann** [aligungr/UERANSIM#249]
hi
When using mcc: 000, the program prompts me  'mnc' is too small.I think you may have overlooked something

**Comment by aligungr** [comment]
Hi @willann.

MCC=0 is an invalid value.

MNC=0 is valid but we don't accept it. (And this is a mistake I think). can fix this if you really need to use mnc=0.

**Comment by willann** [comment]
@aligungr 
thank you 
sorry,I typed it wrong,(When using mnc: 000),in fact mnc=0 is not a mistake.China Mobile's MCC=460 MNC=000

**Comment by aligungr** [comment]
@willann I'll fix this in a day, thanks

**Comment by aligungr** [comment]
@willann I've just fixed the issue. You can try again with latest master branch.

Please let me know if you have any further problems.

Thanks for reporting the issue.
