### ISSUE TITLE
Cant find any UERANSIM Log files

### ISSUE THREAD

**Issue by pragnyakiri** [aligungr/UERANSIM#254]
Hello,

I can't seem to find any log files under UERANSIM folder.
I went through some previous issues while searching something and I came across a mention of global.log file and ue log file.
But I can't seem to find any log file.
I have just installed UERANSIM, so I believe it must be the latest version of UERANSIM.

Am I missing something here ?

Thank you,
Pradnya

**Comment by aligungr** [comment]
Hello Pradyna

Old versions of UERANSIM had logging to file but we removed this feature in v3.0.1 because of performance concerns.

Now all logs are directly printed on the terminal screen and no additional log file is provided.

**Comment by pragnyakiri** [comment]
Oh Ok! Thanks for the quick reply.
