### ISSUE TITLE
uesimtun0 interface MTU 1500 setup Problem

### ISSUE THREAD

**Issue by j13tw** [aligungr/UERANSIM#265]
Hello @aligungr
I try the UERANSIM with kubernetes VIM
and test the reliablity testing with iperf3 / scp / ftp tools
in iperf3 testing, the ipef3 have sometime tell me the message too long
in scp / ftp testing, the download file will pending on the progress bar 0% can't get the file,
So, I think in the UERANSIM on UE side, 
the uesimtun0 tunnel interface set MTU 1500 have some issue
in 5G system GTP-U are have some protocol header define,
gnb will get the UE Message, add on the GTP-U header
like GTP-U([dst-ip][src-ip][dst-port][src-port][gtp])UE(Message)
then the UE setup the MTU 1500 is define the UE request/relpy frame size
In UERANSIM the gnb/ue exchange message is based on UDP Server
, the UDP Message are bearer the UE Request, 
and gnb to UPF message will add the GTP-U
all of then will have break through the MTU 1500 opportunity

In my solution, I try to set the UE side with lower MTU with 1400
protect the UE send MTU less than MTU 1500 after add GTP-U and UDP header 
```ip link set uesimtun0 mtu 1400```
and the download file is work to me.

If this is not an exact solution and issue
please tell me the MTU 1500 work and design pattern on uesimtun0 interface
Maybe my idea is wrong.

<img width="1428" alt="截圖 2021-03-02 上午1 07 10" src="https://user-images.githubusercontent.com/27864573/109532046-a6434480-7af3-11eb-9591-a5d4ecd2e971.png">

**Comment by aligungr** [comment]
Hello @j13tw 

Thanks for reporting this issue. I'm investigating this. Possible solutions are decreasing MTU in UE like you said, or performing GTP fragmentation on gNB side.

I'll let you know after finding a possible solution.

Thank you

**Comment by aligungr** [comment]
@j13tw Hello again. Sorry for the late action.

I reduced the MTU to 1400 in the latest release.

And GTP fragmentation on gNB side is on roadmap and will be implemented in the future.

Thanks again for reporting this.
