### ISSUE TITLE
How about lte ran sim?

### ISSUE THREAD

**Issue by myonlystarWang** [aligungr/UERANSIM#267]
Hi aligungr
     I was test my own epc recently,I just wanna know if you have a lte ran simulation like UERANSIM？

**Comment by aligungr** [comment]
Hi @myonlystarWang 

Unfortunately we don't have one. From the beginning we only focused on 5G SA (Standalone access). LTE/EPC support will be available in the very very far future. and it's not included in the short-term roadmap.

Regards

**Comment by myonlystarWang** [comment]
Hi aligungr,
     Thanks for the quickly response!But do you know of any other open source libraries for LTE RAN simulator?
     By the way,`UERANSIM `is very nice for me.Thank you and the rest of the community for your amazing work!

BR

**Comment by aligungr** [comment]
@myonlystarWang You can look at srsLTE. As far as I know they implemented some minimal UE, RAN, and EPC core network.

**Comment by myonlystarWang** [comment]
Thank you @aligungr 
I am sorry for not close the problem in time!
