### ISSUE TITLE
Some problems occur when starting multiple UEs at the same time

### ISSUE THREAD

**Issue by dongzx666** [aligungr/UERANSIM#277]
I started 10 UEs with the following command and everything was ok, but there were some errors when I changed the number to 20 and 50.
```
nr-ue -c myconfig.yaml -n 10
````
The next two figures are the logs of `nr-ue` when the number of UE is **20**.
![image](https://user-images.githubusercontent.com/19199988/112837900-09160480-90cf-11eb-962e-4940fad8ff27.png)
![image](https://user-images.githubusercontent.com/19199988/112837864-fc91ac00-90ce-11eb-93b9-23c6869ab6bd.png)
The next figure is the logs of `nr-gnb` when the number of UE is **20**.
![image](https://user-images.githubusercontent.com/19199988/112838111-4bd7dc80-90cf-11eb-9f75-115eb80e24c0.png)
The next figure is the logs of `nr-gnb` when the number of UE is **50**.
![image](https://user-images.githubusercontent.com/19199988/112838212-690cab00-90cf-11eb-8022-2ededbeca9c6.png)
Here are the errors involved in the AMF log
![image](https://user-images.githubusercontent.com/19199988/112838651-dc162180-90cf-11eb-93f5-ef97a7a2ce38.png)
![image](https://user-images.githubusercontent.com/19199988/112838683-e506f300-90cf-11eb-9fba-3cdf26497888.png)
So why do these things happen? It seems that Open5GS did not process the UE information sent by GNB in time? 
And when the number of UE is 50, AMF directly terminate the association.
I can't figure out whether this question is about UERANSIM or Open5GS, so I'm sorry to mention issue here first.

**Comment by aligungr** [comment]
Hi @dongzx666

I think there is a core network related problem in this case. `PAYLOAD_NOT_FORWARDED` cause is defined as "abnormal cause"  by 3GPP for registration reject. So, probably some of the things didn't go well in the core-network side.

Perhaps it could be better to open an issue in Open5gs as well.

Thanks for reporting this issue.
