### ISSUE TITLE
SCTP socket could not be created

### ISSUE THREAD

**Issue by ansonmez** [aligungr/UERANSIM#281]
Ubuntu 20.10
libsctp1 (= 1.0.18+dfsg-1)

nr-gnb -c ../config/open5gs-gnb.yaml
UERANSIM v3.1.6
[2021-04-03 15:29:20.677] [sctp] [info] Trying to establish SCTP connection... (127.0.0.5:38412)
terminate called after throwing an instance of 'sctp::SctpError'
  what():  SCTP socket could not be created
Aborted (core dumped)

**Comment by ansonmez** [comment]
Switch back to the Ubuntu 18.04 release 
now it is ok

**Comment by anichari** [comment]
Hi, I know this is closed, but is there a way to get this error to be resolved on Ubuntu 20.04
