### ISSUE TITLE
When ./nr-ue is running, how can I update the configuration information of UE

### ISSUE THREAD

**Issue by dongzx666** [aligungr/UERANSIM#285]
I noticed that Feature Set mentioned UERANSIM implemented **Generic UE Configuration Update**, so When `./nr-ue` is running, how can I update the configuration information of UE?
In fact, when UE is running, I want to switch slices, so I need to update the UE configuration to re-register.

**Comment by aligungr** [comment]
Generic UE Configuration Update is triggered by AMF, and UE is not involved in initiation of this procedure. Therefore you need to trigger the procedure using the core network. See [TS 24.501](https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/15.06.00_60/ts_124501v150600p.pdf) (Section 5.4.4, page 125). And by the way, please note that the Generic UE Configuration Update is partially implemented, i.e some cases does not handled yet in UE side.

**Comment by dongzx666** [comment]
@aligungr Thanks for the answer. I'll take a look at the 3GPP specification document.
