### ISSUE TITLE
[Features]About implementing some features about mobility

### ISSUE THREAD

**Issue by dongzx666** [aligungr/UERANSIM#288]
I saw [issue 279](https://github.com/aligungr/UERANSIM/issues/279) mentioned "handover implementation is delayed, and it will not come in the near future."
And I saw [Feature-Set](https://github.com/aligungr/UERANSIM/wiki/Feature-Set) mentioned "mobility update registration are not implemented yet".
If I want to implement something like these mobility related demos based on UERANSIM, what would you suggest?(like what specifications should I look at, and some other suggestions).
If the final result is satisfactory, I can contribute the implementation to UERANSIM.
Thank you very much.

**Comment by aligungr** [comment]
The wiki page may be outdated in this case, indeed currently we have mobility updating registration, but it's partially initiated.

Mobility updating registration will be triggered in 19 cases, but currently 2 cases are handled.

1. T3512 Expiry
2. T3582 Expiry

---

**Case 1**

T3512 is a NAS timer, and it is started when AMF sends `Registration Accept` message to the UE over NAS layer. By default T3512 has 54min period, but usually it is configured by AMF. ie, AMF sends the value of T3512 to the UE, and then UE uses this value. Therefore you can set T3512 to -for example- 20 seconds. In this way, UE will trigger mobility updating registration after 20 seconds of the initial registration (This type of mobility updating is also called `Periodic Registration`. ie, periodic registration is a special case of mobility registration)

---

**Case 2**

T3582 is a NAS timer as well. But this time it's not configured by AMF, and it's value is always 15sec. T3582 is the re-transmission of PDU session establishment request message timer. Therefore, if the UE sends a PDU session establishment request, and AMF does not respond in (15x5=75seconds), then UE aborts the PDU session establishment procedure, and triggers a mobility updating registration immediately.

---

These 2 cases are already implemented in the latest version of UERANSIM, and other 17 cases will be handled in the future as it is required by UE NAS layer. Perhaps I can also provide manual triggering feature using UE command line interface, if it is requested by the community.

For details about mobility and periodic registration update, see [TS 24.501](https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/15.06.00_60/ts_124501v150600p.pdf) (5.5.1.3)

**Comment by dongzx666** [comment]
@aligungr Thank you for your answer. Do you have any suggestions for handover? I see that I can specify `gnbSearchList`. It would be great if I could trigger the switch of GNB through the command line after starting UE.

**Comment by aligungr** [comment]
@dongzx666 Unfortunately there is no way to trigger a handover at the moment. Currently I'm working on CM-IDLE procedures such as Service Request, Paging etc in these days. And probably I'll start handover procedures after implementing those.

**Comment by dongzx666** [comment]
@aligungr Thank you for your hard work.
