### ISSUE TITLE
Unknown UE by SUCI Error While registering UERANSIM UE to Open5gs

### ISSUE THREAD

**Issue by emorfaq** [aligungr/UERANSIM#293]
Getting Unknown UE by SUCI(Error Rejection 95 5GMM cause: Semantically incorrect message (95)) while registering UE to Open5Gs below are some logs and configuration of my VM. 

root@vbox:~/UERANSIM_LATEST/UERANSIM-3.1.6# build/nr-ue -c config/open5gs-ue.yaml
UERANSIM v3.1.6
[2021-04-17 06:17:34.994] [nas] [debug] NAS layer started
[2021-04-17 06:17:34.994] [rrc] [debug] RRC layer started
[2021-04-17 06:17:34.994] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-04-17 06:17:34.995] [nas] [info] UE connected to gNB
[2021-04-17 06:17:34.995] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2021-04-17 06:17:34.996] [nas] [debug] Sending Initial Registration
[2021-04-17 06:17:34.996] [nas] [info] UE switches to state [MM-REGISTER-INITIATED/NA]
[2021-04-17 06:17:34.996] [rrc] [debug] Sending RRC Setup Request
[2021-04-17 06:17:34.997] [rrc] [info] RRC connection established
[2021-04-17 06:17:35.006] [rrc] [debug] RRC Release received
[2021-04-17 06:17:35.006] [mr] [debug] UE disconnected from gNB [RLS-RRC-NORMAL-RELEASE]
[2021-04-17 06:17:35.007] [nas] [info] UE switches to state [CM-CONNECTED]
**[2021-04-17 06:17:35.007] [nas] [error] Initial Registration failed [SEMANTICALLY_INCORRECT_MESSAGE]**
[2021-04-17 06:17:35.007] [nas] [debug] Handling Registration Reject abnormal case
[2021-04-17 06:17:35.008] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
[2021-04-17 06:17:35.008] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2021-04-17 06:17:35.008] [nas] [info] UE switches to state [CM-IDLE]

root@vbox:~/UERANSIM/build# ./nr-gnb -c ../config/open5gs-gnb.yaml
UERANSIM v3.1.6
[2021-04-17 12:54:53.049] [sctp] [info] Trying to establish SCTP connection... (127.0.0.5:38412)
[2021-04-17 12:54:53.055] [sctp] [info] SCTP connection established (127.0.0.5:38412)
[2021-04-17 12:54:53.056] [sctp] [debug] SCTP association setup ascId[7]
[2021-04-17 12:54:53.056] [ngap] [debug] Sending NG Setup Request
[2021-04-17 12:54:53.075] [ngap] [debug] NG Setup Response received
[2021-04-17 12:54:53.075] [ngap] [info] NG Setup procedure is successful

root@vbox:~# tail -f /var/log/open5gs/amf.log
04/17 06:17:34.998: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:349)
04/17 06:17:34.998: [amf] INFO: [Added] Number of gNB-UEs is now 1 (../src/amf/context.c:1911)
04/17 06:17:34.998: [amf] INFO:     RAN_UE_NGAP_ID[5] AMF_UE_NGAP_ID[6] TAC[1] CellID[0x10] (../src/amf/ngap-handler.c
04/17 06:17:34.998: [amf] INFO: [suci-0-901-70-0000-0-0-0000000001] Unknown UE by SUCI (../src/amf/context.c:1304)
04/17 06:17:34.998: [amf] INFO: [Added] Number of AMF-UEs is now 1 (../src/amf/context.c:1119)
04/17 06:17:34.998: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:131)
**04/17 06:17:34.998: [gmm] INFO: [suci-0-901-70-0000-0-0-0000000001]    SUCI (../src/amf/gmm-handler.c:72)
04/17 06:17:35.000: [gmm] ERROR: [suci-0-901-70-0000-0-0-0000000001] HTTP response error [400] (../src/amf/gmm-sm.c:56**
04/17 06:17:35.000: [amf] WARNING: [suci-0-901-70-0000-0-0-0000000001] Registration reject [95] (../src/amf/nas-path.c
04/17 06:17:35.004: [amf] INFO: UE Context Release [Action:3] (../src/amf/ngap-handler.c:1253)

root@vbox:~# tail -f /var/log/open5gs/udm.log
04/17 05:21:03.359: [app] INFO: UDM terminate...done (../src/udm/app.c:39)
Open5GS daemon v2.2.6

04/17 05:23:39.756: [app] INFO: Configuration: '/etc/open5gs/udm.yaml' (../lib/app/ogs-init.c:129)
04/17 05:23:39.756: [app] INFO: File Logging: '/var/log/open5gs/udm.log' (../lib/app/ogs-init.c:132)
04/17 05:23:39.757: [app] INFO: UDM initialize...done (../src/udm/app.c:31)
04/17 05:23:39.758: [sbi] INFO: nghttp2_server() [127.0.0.12]:7777 (../lib/sbi/nghttp2-server.c:145)
04/17 05:23:40.137: [udm] INFO: [11558de2-9f3d-41eb-a650-553dd66c511e] NF registred [Heartbeat:10s] (../src/udm/nf-sm.
04/17 05:23:46.945: [udm] INFO: [159b59a4-9f3d-41eb-b871-9bee6dcfbf4c] (NRF-notify) NF registered (../src/udm/nnrf-han
04/17 05:23:46.945: [udm] INFO: [159b59a4-9f3d-41eb-b871-9bee6dcfbf4c] (NRF-notify) NF Profile updated (../src/udm/nnr96)
**`04/17 05:35:48.153: [udm] ERROR: [suci-0-901-70-0000-0-0-0000000001] HTTP response error [400] (../src/udm/nudr-handle`**

**amf.yaml**

amf:
    sbi:
      - addr: 127.0.0.5
        port: 7777
    ngap:
      - addr: 127.0.0.5
    guami:
      - plmn_id:
          mcc: 901
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 901
          mnc: 70
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 901
          mnc: 70
        s_nssai:
          - sst: 1
            sd : 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

SIM Profile and open GS

![HSS](https://user-images.githubusercontent.com/43461791/115132738-62839c00-9fc8-11eb-8549-50309c469f51.PNG)
![UE](https://user-images.githubusercontent.com/43461791/115132740-644d5f80-9fc8-11eb-8712-ff7663b60811.PNG)

**Comment by aligungr** [comment]
Thanks for the issue. I think it's a core network or configuration related problem, and I think I could not help in this case.

**Comment by acetcom** [comment]
@emorfaq 

Your log contents are corrupted. Especially line number. So I cannot find your problem. 
Sharing all the log/conf files, pcap and DB subscriptions, etc. as many as possible will be more helpful in analyzing your problem,

Thanks a lot!
Sukchan

**Comment by emorfaq** [comment]
Hi 

> @emorfaq
> 
> Your log contents are corrupted. Especially line number. So I cannot find your problem.
> Sharing all the log/conf files, pcap and DB subscriptions, etc. as many as possible will be more helpful in analyzing your problem,
> 
> Thanks a lot!
> Sukchan

Hi Sukchan,
Here is everything you requested in zip file
[SEMATIC ERROR BY SUCI.zip](https://github.com/aligungr/UERANSIM/files/6340980/SEMATIC.ERROR.BY.SUCI.zip)
. Let me know if anything else you require.



![open5gs]
![open5gs](https://user-images.githubusercontent.com/43461791/115345295-373db000-a174-11eb-9e94-6fb021d56860.PNG)



Thanks

**Comment by acetcom** [comment]
@emorfaq

The UE sends RegistrationRequest message with PLMN-ID 001/01 instead of 901/70.
@aligungr can answer.

Thanks!
Sukchan

**Comment by emorfaq** [comment]
> @emorfaq
> 
> The UE sends RegistrationRequest message with PLMN-ID 001/01 instead of 901/70.
> @aligungr can answer.
> 
> Thanks!
> Sukchan

Sorry Sukchan. I might have ran the wrong UE Config file last time. here is the correct UE and pcap zip
[SEMATIC ERROR BY SUCI_2.zip](https://github.com/aligungr/UERANSIM/files/6342850/SEMATIC.ERROR.BY.SUCI_2.zip)

UE is sending the correct plmn. 
![new cap](https://user-images.githubusercontent.com/43461791/115383568-995ddb80-a19b-11eb-8092-e7c3642a11f3.PNG)

**Comment by acetcom** [comment]
@emorfaq 

```diff
$ diff -u udr.yaml.old udr.yaml
--- udr.yaml.old	2021-04-05 15:04:30.000000000 +0900
+++ udr.yaml	2021-04-07 00:17:14.000000000 +0900
@@ -77,7 +77,7 @@
 #
 udr:
     sbi:
-      - addr: 127.0.0.20
+      - addr: 127.0.0.10
         port: 7777
```

You use the same IP address (127.0.0.10) for UDR and NRF. So, it does not work properly.

Good luck with you!
Sukchan

**Comment by emorfaq** [comment]
Thanks, Sukchan!!! Resolved now. Maybe I did some silly mistake. I ll keep that in mind
