### ISSUE TITLE
UERANSIM & Open5gs Connectivity Problem

### ISSUE THREAD

**Issue by jpsla94** [aligungr/UERANSIM#310]
Hello All,

I have just installed UERANSIM and Open5gs in a Ubuntu virtual machine following Nick Vs Networking tutorial https://nickvsnetworking.com/my-first-5g-core-open5gs-and-ueransim/. The emulated device in UERANSIM cannot connect to the internet, i have try to ping google.com but i can get a response back.

What am I missing where?

In attachment, i have my Open5gs UERANSIM files and log and Open5gs amf file:

[amf.txt](https://github.com/aligungr/UERANSIM/files/6415323/amf.txt)
[open5gs-gnb.txt](https://github.com/aligungr/UERANSIM/files/6415283/open5gs-gnb.txt)
[open5gs-ue.txt](https://github.com/aligungr/UERANSIM/files/6415284/open5gs-ue.txt)
![Screenshot from 2021-05-03 15-12-11](https://user-images.githubusercontent.com/32711664/116888202-14ef6c00-ac23-11eb-9aac-b5d8aab679aa.png)

**Comment by aligungr** [comment]
Hello @jpsla94, Please use 2 different machines for UERANSIM and Open5GS as descried in the Wiki Page. (And don't forget to configure UPF GTP IP address as besides AMF)

**Comment by jpsla94** [comment]
@aligungr I reading the tutorial again and saw that in order to to work correctly I had to implement the open5gs and UERANSIM on two separate VMs. This hasn´t clear to me at first, because it hasn´t mention clearly in plain text.

**Comment by aligungr** [comment]
No worries @jpsla94, and please let me know if you have any further questions.

**Comment by jpsla94** [comment]
My issue is fix. Thank you so much for your help, @aligungr.

**Comment by Wriddhiraaj** [comment]
> @aligungr I reading the tutorial again and saw that in order to to work correctly I had to implement the open5gs and UERANSIM on two separate VMs. This hasn´t clear to me at first, because it hasn´t mention clearly in plain text.

Hi, could you guide me what were the changes you did in the configuration files while deploying in different vms

**Comment by LSKhappychild** [comment]
@aligungr  Hi. It has been a while since this issue was initially raised, and I wonder if your advice (run UERANSIM and core network in different VMs) is still valid now.
