### ISSUE TITLE
[rls] [error] Unable to decode RLS message

### ISSUE THREAD

**Issue by lee850220** [aligungr/UERANSIM#313]
when I upgrade to v3.1.8, the config cannot work and show the error as title.

But this config can work with v3.1.7 and older.
[config.zip](https://github.com/aligungr/UERANSIM/files/6424673/config.zip)

**Comment by aligungr** [comment]
It should not be relared to config files, but here's the first thing comes to my mind:

Both UE and gNB must be the same version.

For example if UE is v3.1.7 and gNB is v3.1.8, then you may encounter this error.

**Comment by lee850220** [comment]
@aligungr Thanks for your reply.

After I re-compile UERANSIM, the problem is solved.
