### ISSUE TITLE
uesim interface mac address

### ISSUE THREAD

**Issue by jpsla94** [aligungr/UERANSIM#314]
Hello,

I am trying to generate some random traffic from my device using ostinato traffic generator. But I came across a issue, uesim interface doesn´t possess an MAC address. How do I get a mac address for usimtun interface? 

Want application have successfully run with nr-binder besides firefox?

BR,
João Lola

**Comment by aligungr** [comment]
Hello @jpsla94 

`uesimtunX` interface does not support MAC address at the moment (it will in the future though). And I'm not sure how we can find a workaround about this problem.

Regards

**Comment by jpsla94** [comment]
Thanks for answer @aligungr. Is possible to use nr-binder on `uesimtunX ` to generate random traffic instead? Because the way I am generating traffic in ostinato is producing different results from those I want.

**Comment by aligungr** [comment]
Yes, sure. You can even write a very simple program in a few lines of code yourself. The only thing you need to do is to bind the program using nr-binder.

nr-binder should work almost all apps. (i.e. not just curl, or firefox)

I mean, you need two things:

1. Traffic generator (You can write one by yourself for example, or use firefox, or use some other advanced tools)
2. nr-binder

In UERANSIM we already have nr-binder, but for traffic generation there is none.

I hope this will be helpful

**Comment by jpsla94** [comment]
Yes, it is helpful. Thanks @aligungr.

**Comment by jpsla94** [comment]
This is my output in wireshark, using `uesimtunX` to`enp0s8` icmp packets:
![2021-05-06 18_08_14-ueransim  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/32711664/117338142-212f2f80-ae96-11eb-883a-00ce6671d577.png)
