### ISSUE TITLE
[Question] how to rebuild UERANSIM again?

### ISSUE THREAD

**Issue by Evanlin1224** [aligungr/UERANSIM#321]
hello @aligungr 
i come back again, i build another VM as UE2, and i git UERANSIM that is the master version(v3.1.9). When i access my gnb, it's error,"PLMN selection failure, no cell available".Then I go back to see my UE1's config(v3.1.7), it's as same as UE2's config. Then i guess that it's version problem. I want to know how to rebuild UERANSIM again .Becasue i tried command "make clean", but it can't , Thanks.

**Comment by aligungr** [comment]
Hello @Evanlin1224 

The problem may be still configuration related, even the configs of UE1 and UE2 are the same.
Perhaps UE1 has access to gNB's machine but not UE2.
Are UE1 and gNB in the different machines, or same machine?

---
If the configuration is not the problem, versions may be so, tough.

`make` command always cleans automatically and rebuilds UERANSIM. No further action is required. My suggestion is please make sure that,
1. You kill all gNB and UE processes in all machines
2. Rebuild UERANSIM in all machines with fresh clone from GitHub
3. Start UE and gNBs again.

---

**Comment by Evanlin1224** [comment]
hello @aligungr 
My UE1 ,UE2 and gNB are in the different machine. I am sure that configuration is the same. I have tried use v3.1.7 to run "build/nr-ue -c config/open5gs-ue.yaml", and it still show "[nas] [error] PLMN selection failure, no cell available".By the way UE1 can connect gNB normally.

**Comment by aligungr** [comment]
@Evanlin1224

I've just checked your situation in my environment just in case to see if we have a bug about it, but it works in my case.

Perhaps there is another problem. Please send all log, configurations and PCAP files captured from each of the VM, and `ifconfig` outputs in the machines. Hopefully we can figure the issue out with the help of these information.

**Comment by Evanlin1224** [comment]
hello @aligungr 
I thinks that it's my fault. When I tried to config another DNN and interface on core network(ogstun2), it's OK!!!!!!
Thanks for your suggestion!!!!!
