### ISSUE TITLE
Cannot discover SMF & UERANSIM UE routing failure

### ISSUE THREAD

**Issue by sv1ple** [aligungr/UERANSIM#323]
Hello,

I have followed the setup described here: https://github.com/s5uishida/open5gs_5gc_ueransim_sample_config#table-of-contents
Open5GS version: 2.2.6
UERANSIM version: 3.1.7

The UERANSIM gNB is properly attached to the AMF.
However, when I launch UE0, I receive the following errors:

UERANSIM UE output:

    [2021-05-17 13:50:47.018] [nas] [debug] Sending PDU Session Establishment Request
    [2021-05-17 13:50:47.224] [nas] [error] PDU Session Establishment Request received due to a routing failure
    [2021-05-17 13:50:47.224] [nas] [debug] Aborting SM procedure for PTI[1], PSI[1]

The interface uesimtun0 does not appear.

AMF Log:

    05/17 13:50:47.223: [gmm] INFO: UE SUPI[imsi-001010000000000] DNN[internet] S_NSSAI[SST:1 SD:0xffffff] (../src/amf/gmm-handler.c:822)
    05/17 13:50:47.225: [amf] ERROR: Cannot discover [SMF] (../src/amf/sbi-path.c:237)
    05/17 13:50:47.225: [amf] WARNING: [suci-0-001-01-0000-0-0-0000000000] 5GSM reject (../src/amf/nas-path.c:485)

I also attach the UERANSIM-UE pcap file.
ue.zip

Is there any insight on this issue?

Thank you.
[ue.zip](https://github.com/aligungr/UERANSIM/files/6522306/ue.zip)

**Comment by aligungr** [comment]
@sv1ple

It seems like a core network related problem. But I think:

- Your SD value may be incorrect in configurations; or
- SMF may not be running

Regards

**Comment by sv1ple** [comment]
Thank you @aligungr!
It seems the SMF function wasn't running due to a mistake in its yaml file.

Problem solved!
