### ISSUE TITLE
UERANSIM cli status command output

### ISSUE THREAD

**Issue by DendoD96** [aligungr/UERANSIM#326]
Hi @aligungr , 
I have a question about the response to the status command: the pdu session list does not contain information about sst, sd and dnn. When I have several sessions established it is not possible to know the slice to which they refer. Is there a reason this information is not being shown or is it just to avoid too "heavy" output?
Thank you, 
Daniele

**Comment by aligungr** [comment]
@DendoD96 

Actually no, the only reason was my laziness :) I think we should provide as much information as possible in the `status` command. I will include the additional information you mentioned in the next version. (Next version will be released in this week)

Thanks for requesting this feature

**Comment by DendoD96** [comment]
@aligungr 
I agree with u. I added the information related to s-nssai and dnn. I could try to add QoS related information and open a pull request. Or I'll wait for next week :)

**Comment by aligungr** [comment]
I would appreciate if you can open a pull request, but otherwise no problem of course, I would check this in a few days.

**Comment by aligungr** [comment]
@DendoD96 

> In order to display the QoS information and the session ambr is necessary to implement some ToJson methods right? I have not found any method.

Yes, it is necessary to implement a `ToJson` overload for custom types such as QoS info and AMBR etc. You can check for the existing overloads in the code-base for reference.

> is it possible that the parsing of the AMBR is not entirely correct? For example: using 5 Mbps as a value, the IESessionAmbr object has 4Mbps as a unit and 1 as a value.

I'm not really sure if we have a bug about it. I've just checked it, but could not notice a mistake.

---

I'll merge your PR request, but waiting to hear from you about other fields such as QoS etc.

Thanks again for the PR

**Comment by DendoD96** [comment]
Hi @aligungr,
sorry for the late response, i have been busy in these days. Ok no problem, hope to be able to re-contribute in the future.

**Comment by aligungr** [comment]
Sure @DendoD96, by the way I moved PDU session information from `status` command to `ps-list` command, FYI.
