### ISSUE TITLE
From where I can check UE interface?

### ISSUE THREAD

**Issue by PallaviTharigonda** [aligungr/UERANSIM#331]
Hi @aligungr ,I'm just looking in code from where uesimtun interfaces are creating?Can you please tell me where in code it's available

**Comment by aligungr** [comment]
@PallaviTharigonda 

`uesimtunX` interfaces are created in the following source file: `src/ue/tun/config.cpp`

**Comment by PallaviTharigonda** [comment]
Thank you and I'm closing this issue
