### ISSUE TITLE
NAT support

### ISSUE THREAD

**Issue by bluehat-f** [aligungr/UERANSIM#336]
When a GNB running in a docker container(default network mode), there is a NAT between gNodeB and UPF. At the moment there is only "gtpIp" in config file, which is for GNB N3 listening port and is also sent to UPF by F-TEID. 
Is it possible to add a gtpIp for only advertising to UPF in F-TEID? For example, a gtp_Advertise_Ip is configured in yaml file and it's only for filling in F-TEID, which is sent to UPF. The original gtpIp is for listening but not sent to UPF.

**Comment by aligungr** [comment]
@bluehat-f 

That was a very good question.

I've just added this feature exactly like you proposed. Now you can set `gtpAdvertiseIp` in the gNB config file if you want to override the IP address to be used by UPF. (I didn't include this field in the sample config files, but it's documented in the wiki page.)

Example usage in `gnb.yaml` file:

```yaml
...
gtpIp: 192.168.1.33
gtpAdvertiseIp: 85.99.50.12
...
```

Thanks

**Comment by bluehat-f** [comment]
Very Nice. Thanks for your great project again.
