### ISSUE TITLE
Running the UE part on a seperate VM

### ISSUE THREAD

**Issue by aviweit** [aligungr/UERANSIM#342]
Hi,

I have a UERANSIM setup that properly works with free5gc deployment. UERANSIM runs both gnb and UE on the same VM.
I would now like to have multiple UEs running on separate VMs.

I have created another fresh VM, installed UERANSIM and edited UE configuration part with a supi, key and op (that I have subscribed before with the webui) along with gnbSearchList that points to the gnb VM. I also updated SMF configuration file (uerouting) with the new supi.

I successfully created pdu session for the first one, but when creating such for the second one AMF reports a duplication in session ID:

```
2021-06-06T13:43:09Z [WARN][AMF][GMM][AMF_UE_NGAP_ID:2][SUPI:imsi-208930000000003] Duplicated PDU session ID[1]
```

I would like to ask whether this scenario is supported?

Thanks.

**Comment by aligungr** [comment]
Hi @aviweit 

There is no limitation in UERANSIM about the scenario you mentioned. You can use any number of UEs in any environment to connect any gNB.

However I think it can be a SUPI problem. Please make sure that all UEs have a different SUPI from each other.

Regards

**Comment by aviweit** [comment]
Hi @aligungr ,

It is working for me now.
Thanks.

**Comment by minziran** [comment]
> Hi @aligungr ,
> 
> It is working for me now. Thanks.

Hi, I met the same problem. I have double checked all the supi. They are different from each other. Would you minding sharing your solution?
Thanks.
