### ISSUE TITLE
m_logger does not print strings properly

### ISSUE THREAD

**Issue by pragnyakiri** [aligungr/UERANSIM#343]
Hello

I am using m_logger to print some values of variables.
But am always facing issues while printing strings.

The following statement prints random characters which are not readable in place of "%s".
m_logger->debug("amf->amfName: %s", amf->amfName);

Whereas this statement prints a readable string "AMF"
std::cout << "amf->amfName: " << amf->amfName << "\n" ;

Even though amf->amfName is of type std::string, m_logger is not printing the string properly.

Is this a bug ?

Thanks,
Pradnya

**Comment by aligungr** [comment]
Hello @pragnyakiri 

Logger does not accept `std::string` but it accepts a `char*`

So please use for example `amfName.c_str()`, instead of only `amfName`.

You can find examples about `c_str()` in our codebase.

Good luck

**Comment by pragnyakiri** [comment]
Oh yes!

Thank you so much!
