### ISSUE TITLE
AMF connection fails after activation of UE

### ISSUE THREAD

**Issue by zalfia** [aligungr/UERANSIM#346]
Hi,

invoking the gnb  OK
when invoking the UE - errors appear on the gnb console and connection to AMF fails

please see attached:
- gnb console
- ue console
- pcap file
[UE.txt](https://github.com/aligungr/UERANSIM/files/6648161/UE.txt)
[gNB.txt](https://github.com/aligungr/UERANSIM/files/6648162/gNB.txt)

[RLS&SCTP.zip](https://github.com/aligungr/UERANSIM/files/6648164/RLS.SCTP.zip)

Thanks !

**Comment by zalfia** [comment]
also attached AMF & N3IWF console messages with relevant errors
[n3iwf.txt](https://github.com/aligungr/UERANSIM/files/6648417/n3iwf.txt)
[amf.txt](https://github.com/aligungr/UERANSIM/files/6648418/amf.txt)

**Comment by aligungr** [comment]
Hi @zalfia

I could not detect an error in UE or gNodeB side, however it looks like free5gc crashes after the UE starts. Perhaps it's convenient to open an issue in free5gc side.

Regards

**Comment by zalfia** [comment]
Hi Ali,

thanks for your prompt reply.
I've opened an issue with free5gc.

https://github.com/free5gc/free5gc/issues/209
