### ISSUE TITLE
Field 'mnc' has invalid type

### ISSUE THREAD

**Issue by zhx200808** [aligungr/UERANSIM#350]
Hi @aligungr

In  the GNB config file , if i set the  mnc: '08' , i will get the error as below, please check, thanks.

ERROR: Field 'mnc' has invalid type.

Thanks,
Xin
![mnc_error](https://user-images.githubusercontent.com/35137780/122758525-79e24c80-d2cb-11eb-83de-107c4ab4ca58.png)

**Comment by aligungr** [comment]
@zhx200808 

There is a strange bug in YAML parsing code, but I could not detect it yet. MNC field does not work for `08` and `09` but the other values seem working. You can try to use a different MNC for a workaround

BR

**Comment by zhx200808** [comment]
@aligungr thanks for your tips. you are right , the other mnc value work fine.

**Comment by DendoD96** [comment]
I @aligungr , i have just open a [pull request](https://github.com/aligungr/UERANSIM/pull/356) for this issue.

Regards

**Comment by aligungr** [comment]
@zhx200808 This issue has been fixed now. You can try with the latest code.

**Comment by zhx200808** [comment]
@aligungr @DendoD96 thanks guys, no this issue with the new version now.
