### ISSUE TITLE
Connecting UEs through different gnodeBs to same UPF (Free5gC)

### ISSUE THREAD

**Issue by mharris-t** [aligungr/UERANSIM#360]
Hi,

I am trying to connect two UEs through different gNodeBs connected to the same 5G core. I would like to establish connectivity between the UEs. So far, I am able to connect the UEs through their own gNodeBs and establish connectivity to the internet. However, there is no connectivity between them. 

![image](https://user-images.githubusercontent.com/60294955/124112228-c1f33300-da72-11eb-9199-ac3a226ee589.png)

Both the UEs get the PDU session IPs in the same subnet. That is, 60.60.0.0/8

**Comment by aligungr** [comment]
Hi @mharris-t 

It's kind of complicated...

Please see https://github.com/aligungr/UERANSIM/issues/270

In short, it seems that it is expected behavior.

**Comment by mharris-t** [comment]
@aligungr , thank you very much for responding. I have already gone through that, it seems like this is a tough one to crack. One question I have is, is there a possibility of sharing same UPF for two different gNBs in the implementation? If yes, what would my SMF configuration look like?

**Comment by aligungr** [comment]
@mharris-t 

Yep, it's possible to share the same UPF for different gNBs.

But I really don't know if free5gc supports this, and how to configure SMF in free5gc for this purpose.

Please let me know if you have any other questions

**Comment by mharris-t** [comment]
I will see if I can get some solution to the issue from the free5gc repo. If I do, I will close this issue. If not, I will close it after a while. Thank you very much for your help!

**Comment by mharris-t** [comment]
Was able to establish end-to-end connectivity from UE to a remote host in the DN. Unfortunately, could not find a way to build the network with two gNBs for E2E connection between UEs.
