### ISSUE TITLE
Throughput over the TUN interface.

### ISSUE THREAD

**Issue by NAYANSEN90** [aligungr/UERANSIM#370]
Is there a KPI on the userplane throughput with the TUN interface?  
Is it possible to run 1Gbps worth of data through it.  

I see that the tun interface has speed of 10M? Will changing the speed using ethtool help?

**Comment by aligungr** [comment]
When I test our TUN interface, I had experienced around ~2Gbps within a custom environment. Actually, the throughput highly depends on the machines and the network.

But still, there is a room for optimizations in our UE's throughput. I'll improve the performance and reduce latency of the software. But I'm not able to allocate some time these days.

**Comment by NAYANSEN90** [comment]
Thanks. I'll try to do a KPI and see what I get.

**Comment by aligungr** [comment]
I used **nr-binder** and **firefox**, and utilized one of the speed test websites.

**Comment by NAYANSEN90** [comment]
I have been trying iperf3 and get very low throughput about 10Mbps ( the link speed of the tun interface).  

I have tried iperf3 tcp, it stablises at around 10Mbps.  
I have tried iperf3 udp, during UL I see around 10Mbps max ( measuring at N3 on the UPF)
I have tried iperf3 udp, DL using Reverse send, I see the desired speed on N3 of UPF (whatever I send),  but the iperf3 client end on the UE still sees around 10Mbps, and shows huge loss.

All in all it seems the net link throughput gets limited to the TUN interface speed. 

The cpu usage of nr-gnb and nr-ue is very nominal, so it is not the code per se.

Any ideas?

**Comment by NAYANSEN90** [comment]
TCP throughput:
Cmd: ./nr-binder 60.60.0.7 iperf3 -c iperf3-service -t 30 -i 1
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  49.3 MBytes  13.8 Mbits/sec  167             sender
[  5]   0.00-30.01  sec  45.8 MBytes  12.8 Mbits/sec                  receiver

UDP Througput UL : 
Cmd: ./nr-binder 60.60.0.7 iperf3 -u -c iperf3-service -t 30 -i 1 -b 50M

[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-30.30  sec   179 MBytes  49.5 Mbits/sec  0.000 ms  0/139086 (0%)  sender
[  5]   0.00-31.70  sec  43.3 MBytes  11.5 Mbits/sec  1.231 ms  105388/139067 (76%)  receiver

UDP Throughput DL: 
Cmd:  ./nr-binder 60.60.0.7 iperf3 -u -c iperf3-service -t 30 -i 1 -b 50M -R
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-30.08  sec   179 MBytes  50.0 Mbits/sec  0.000 ms  0/139463 (0%)  sender
[  5]   0.00-30.00  sec  49.4 MBytes  13.8 Mbits/sec  5.221 ms  100618/139074 (72%)  receiver

For the UDP throughputs I measured across the UPF N3 and N6 and found no drops. I am using free5gc as SA core.

**Comment by NAYANSEN90** [comment]
Sorry. I found the bug, I was using a docker container and there was a cgroup resource limit on the container. So the entire container was cpu bound. I am getting around 500Mbps.  
That is better than previous observations.  
Sorry for the trouble. :)

**Comment by NAYANSEN90** [comment]
I was running the ueransim inside a k8s pod. I simply increased the number of cpu in the resource of the yaml.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HaQuocToan** [comment]
![image](https://github.com/aligungr/UERANSIM/assets/89145535/f314b7ba-0a35-4fb6-adec-ef6c20991b5a)
why is there this difference?, (i executed 2 commands consecutively). thanks
