### ISSUE TITLE
Sequence Number, NAS Count?

### ISSUE THREAD

**Issue by p3ngdump** [aligungr/UERANSIM#374]
Hi aligungr!

I have a question about the UERANSIM project.

When NAS messages are exchanged between the gNB and the UE, is there an increase in the sequence number or an increase in NAS COUNT?

From what I've checked, it looks like the NAS COUNT value is fixed at 0.

I would appreciate it if you could let us know about that information.

Thank you!

**Comment by aligungr** [comment]
Hi @p3ngdump 

More precisely, NAS messages are not exchanged between UE and gNB, but they are exchanged between UE and AMF. But the gNodeB is only a transparent container for NAS messages between UE and AMF in N1/N2 interface.

---

Sequence number is derived from NAS COUNT. And NAS COUNT is incremented after each NAS message encryption. In our UE, NAS COUNT is **not** fixed at 0. But for the initial NAS messages, it is normal to have a 0 sequence number, before the security is activated.

**Comment by p3ngdump** [comment]
Thanks for your kind reply. @aligungr 

I have one more question. 

Does the UE in UERANSIM perform MAC verification (integrity protection) normally? Or is it still in need of further implementation?
I thought NAS COUNT was the problem with MAC validation while using UERANSIM. However, since you explained that the COUNT value normally increases, I wonder if MAC verification works properly.

I apologize for my lack of questions.(limitation of knowledge)

Thank you!

**Comment by aligungr** [comment]
@p3ngdump

Our UE fully implements NAS encryption mechanism, including MAC validation.

If you are having trouble with MAC validation, I think UE keys or other configuration issues are usually the root cause.

**Comment by p3ngdump** [comment]
@aligungr 

Thank for your kind reply!!

**Comment by p3ngdump** [comment]
@aligungr 

Thank for your kind reply!!!!
