### ISSUE TITLE
UERAN container ping failed

### ISSUE THREAD

**Issue by minziran** [aligungr/UERANSIM#378]
I added the iptables command mentioned in https://githubmemory.com/repo/free5gc/free5gc-compose/issues/26?page=1

The ping still failed.

![uerancontainer](https://user-images.githubusercontent.com/18386584/129619417-4867f3c6-a009-4a72-bb70-43de21e64bbb.png)

Thank you for your time and help!

**Comment by aligungr** [comment]
Hi @minziran 

I could not detect an error in the first look but, you are using very old version of UERANSIM. Updating it and a performing a fresh install may solve the issue.

**Comment by minziran** [comment]
@aligungr Thank you for reply. I will update the UERANSIM version.

I found two errors while running the old version.

After running docker-compose up
nrf | 2021-08-17T16:11:14Z [INFO][NRF][MGMT] Create NF Profile

nrf | 2021-08-17T16:11:14Z [INFO][NRF][MGMT] Location header: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances/15cbd9c6-1167-4224-9461-31d486851da6

nrf | 2021-08-17T16:11:14Z [INFO][NRF][GIN] | 201 | 10.100.200.14 | PUT | /nnrf-nfm/v1/nf-instances/15cbd9c6-1167-4224-9461-31d486851da6 |

nrf | 2021/08/17 16:11:14 http2: server connection error from 10.100.200.13:48868: connection error: PROTOCOL_ERROR

After running sudo build/nr-ue -c config/free5gc-ue.yaml
sudo build/nr-ue -c config/free5gc-ue.yaml

Then I tried ping -I uesimtun0 127.0.0.1 still failed.

Thank you in advance.

**Comment by hxx-98** [comment]
> I added the iptables command mentioned in https://githubmemory.com/repo/free5gc/free5gc-compose/issues/26?page=1
> 
> The ping still failed.
> 
> ![uerancontainer](https://user-images.githubusercontent.com/18386584/129619417-4867f3c6-a009-4a72-bb70-43de21e64bbb.png)
> 
> Thank you for your time and help!


hi, i met same issue,is there a solution?
thx
