### ISSUE TITLE
error : static assertion failed 

### ISSUE THREAD

**Issue by Nawi98** [aligungr/UERANSIM#382]
Hello @aligungr hope u're doing good...

I m running Raspbian 32-bit version on my Raspberry PI 4.

I installed all the dependencies then installed cmake with that link https://vitux.com/how-to-install-cmake-on-ubuntu/ 'cause the command sudo snap install cmake --classic didn't work for me.

I got into the UERANSIM directory and ran the make command

**Here is the compilation error I've got:**
![IMG-20210821-WA0005](https://user-images.githubusercontent.com/87074904/130357735-270ea248-c686-4994-bdbf-14f5a444569d.jpg)

To understand how the function static_assert works, went though that link https://docs.microsoft.com/en-us/cpp/cpp/static-assert?view=msvc-160

But don't really know what to change in the /root/UERANSIM/src/utils/common.cpp file so that uint64_t will have a 'long' size. 

Could u please help me.

Best regards...

**Comment by aligungr** [comment]
Hello @Nawi98 

UERANSIM currently supports only **64-bit** machines. So Raspbian 32-bit will not work.

I'll fix this soon and inform you.

Cheers

**Comment by Nawi98** [comment]
Hi @aligungr 
Ok just moved on a 64-bit one then everything went fine.
Thx again.
Regards
