### ISSUE TITLE
UE unable to register to free5gc & invalid imsi

### ISSUE THREAD

**Issue by williamlin0504** [aligungr/UERANSIM#387]
I have successfully run up my free5gc gnb,
![image](https://user-images.githubusercontent.com/25023734/131459593-8c356d44-ca49-4664-8bcf-f38848428895.png)
And then when I run the ue part it always shows this:
![image](https://user-images.githubusercontent.com/25023734/131459447-194af6e0-ba7d-4d3a-b64c-eaf59d2755dc.png)

Other things to tell, I have tried to use the command `sudo ./nr-ue -c ../config/free5gc-ue.yaml -i imsi-208930000000003`
It shows:
![image](https://user-images.githubusercontent.com/25023734/131459785-47f5012a-0a37-4ca8-a9bc-6389229ce707.png)
And here is my free5gc-ue.yaml
<img width="636" alt="CU nano" src="https://user-images.githubusercontent.com/25023734/131459849-3bf2aeb6-57e5-4b52-bb04-10f5060fbda3.png">

I am running free5gc on docker-compose.
I only changed the free5gc-gnb.yaml, and leave the rest as initial.
Is there any way to solve this?

**Comment by infinitydon** [comment]
Are you able to ping the UPF from your UERANSIM container? Also make sure you are using the right IP for `gtpIp` in your gnb configuration.

**Comment by aligungr** [comment]
@williamlin0504 I fixed the invalid IMSI error just now. For the other problem we need the core network logs to figure out. Thanks.

**Comment by williamlin0504** [comment]
> Are you able to ping the UPF from your UERANSIM container? Also make sure you are using the right IP for `gtpIp` in your gnb configuration.
@infinitydon Yes, I can ping upf1 from my EC2
![image](https://user-images.githubusercontent.com/25023734/132159848-f3a52911-cfbc-4086-957f-734bfaa25eed.png)

And I sure did use the right IP for `gtpIp` as my EC2 `eth0` IP which I did the same as the `ngapIp`

**Comment by williamlin0504** [comment]
> @williamlin0504 I fixed the invalid IMSI error just now. For the other problem we need the core network logs to figure out. Thanks.

![image](https://user-imags.githubusercontent.com/25023734/132162387-5583cdd2-9435-4442-a69f-3820043a3532.png)
@aligungr Here's the log in my `upf1` container

**Comment by williamlin0504** [comment]
It turns out to be my EC2 has auto upgrade the kernel to 5.11.0 for dome reason.
I redo the downgrade and it seems to work out well.
Thanks. 
![image](https://user-images.githubusercontent.com/25023734/132172046-eed8d468-daff-48aa-9dee-e7dc3bb3a4a0.png)
