### ISSUE TITLE
After Deregisteration, the UE can not register to free5gc

### ISSUE THREAD

**Issue by namssob** [aligungr/UERANSIM#395]
Hi Aligungr
Environment:
free5gc v3.0.5
ueransim: v3.2.2

I use cli to deregister ue with command ./nr-cli imsi-208930000000003 -e "deregister normal" and the ue can not register to free5gc for the second initialization. (This will also face initial random conflict like https://github.com/aligungr/UERANSIM/issues/392)
It seems that the second registration is almost completed, except the the free5gc does not receive the UL NAS RegistrationComplete from UEransim. Therefore, it will do the retransmit the NAS registration accept. 

The logs:
**UERansim:**
![Screenshot 2021-09-08 171355](https://user-images.githubusercontent.com/3509337/132482114-cea9a369-898c-4737-9087-225455a0c02d.png)

**Free5gc:**
[free5gc.log](https://github.com/aligungr/UERANSIM/files/7127688/free5gc.log)

**Pcap:**
[deregister.zip](https://github.com/aligungr/UERANSIM/files/7127697/deregister.zip)

**Comment by Evanlin1224** [comment]
Hi, @namssob @aligungr 
I also met this problem to open5gs

**Comment by aligungr** [comment]
It should be fixed now, please try again with the lates code.

**Comment by namssob** [comment]
Hi, @aligungr 
The random ID error is gone in v3.2.4. But the PDU session still can not establish for the registration after deregistration. It seams that the UE has received the  NAS registration accept, but consider it as a replayed NAS. Therefore, it will not trigger the following steps:  NAS registration complete and NAS  pdu establish.




<img width="683" alt="螢幕擷取畫面 2021-10-03 071351" src="https://user-images.githubusercontent.com/3509337/135734278-7dcdfe1d-6e32-4943-8c14-1e12632aa125.png">
<img width="960" alt="螢幕擷取畫面 2021-10-03 072613" src="https://user-images.githubusercontent.com/3509337/135734261-417f45ca-f872-457d-a237-acc48a19972e.png">

The normal log:
<img width="674" alt="螢幕擷取畫面 2021-10-03 071100" src="https://user-images.githubusercontent.com/3509337/135734238-3952e253-7041-42fb-a61b-a616987d8cc1.png">


[Deregister.zip](https://github.com/aligungr/UERANSIM/files/7272391/Deregister.zip)

**Comment by aligungr** [comment]
@namssob I think there was a bug in NAS replay protection mechanism. Please try again with the latest code.

**Comment by namssob** [comment]
![Screenshot 2021-10-05 153052](https://user-images.githubusercontent.com/3509337/135980317-f0b09fe7-a95c-49c1-889c-b8eccda90fe6.png)

Hi @aligungr 
The registration after deregistration will success in the master branch.
