### ISSUE TITLE
UERANSIM Curl Problem

### ISSUE THREAD

**Issue by minziran** [aligungr/UERANSIM#398]
I can use uesimtun0 to ping but I can not use it to curl the free5GC webserver, which is running in another container. I also tried without uesimtun0 interface. It is able to curl the free5GC webserver.
 
![image](https://user-images.githubusercontent.com/18386584/133093209-0b4bccd5-e94e-4d01-b39a-e9d4fcd9bf84.png)

Thanks in advance!

**Comment by aligungr** [comment]
@minziran The UPF may not be able to route packets targeted to an IP address in your local subnet (which is 192.168.56.103). UPF's virtual interface has a NAT through the **external** interface. Therefore this error may be normal. (It depends on the UPF's behavior, actually).

**Comment by aligungr** [comment]
@minziran The UPF may not be able to route packets targeted to an IP address in your local subnet (which is 192.168.56.103). UPF's virtual interface has a NAT through the **external** interface. Therefore this error can be considered normal. (It depends on the UPF's behavior, actually).

**Comment by minziran** [comment]
> The UPF may not be able to route packets targeted to an IP address in your local subnet (which is 192.168.56.103). UPF's virtual interface has a NAT through the **external** interface. Therefore this error can be considered normal. (It depends on the UPF's behavior, actually).

Thank you for your reply!
The upf code I used is from https://github.com/free5gc/free5gc-compose
Is there any ways can fix this problem?
