### ISSUE TITLE
TEID mismatch after service request

### ISSUE THREAD

**Issue by namssob** [aligungr/UERANSIM#408]
Environment:
Free5gc: v3.0.5
UEransim: v3.2.4

Root cause: Since the TEID in UPTransportLayerInformation of the AN tunnel information has been changed in the InitialContextResponse but it does not take effect on GNB (or uesimtun0).

<img width="955" alt="螢幕擷取畫面 2021-09-30 213500" src="https://user-images.githubusercontent.com/3509337/135465753-d27203c2-7c05-4a6b-bfe1-56911e578020.png">

<img width="959" alt="螢幕擷取畫面 2021-09-30 213550" src="https://user-images.githubusercontent.com/3509337/135465763-35204850-dc98-4c54-9c9f-29e1e3415c00.png">

<img width="937" alt="螢幕擷取畫面 2021-09-30 213151" src="https://user-images.githubusercontent.com/3509337/135465728-c25b5c7c-bb95-4c1c-b2e2-6e220c632b7f.png">

[serviceRequest_UERansim_Fail.zip](https://github.com/aligungr/UERANSIM/files/7259826/serviceRequest_UERansim_Fail.zip)

**Comment by aligungr** [comment]
@namssob This error should be fixed now, you can try again with the latest code.
