### ISSUE TITLE
Specify/fix uesimtun0  ip address

### ISSUE THREAD

**Issue by minziran** [aligungr/UERANSIM#427]
Currently, the uesimtun0 ip address is randomly generated after running "/build/nr-ue -c /config/free5gc-ue,yaml".
ie. [app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun0, 60.60.0.3] is up.
Can we just specify the ip address, so we can utilize the uerouting.yaml for configuring SMF?

Thanks in advance!

**Comment by aligungr** [comment]
Hi @minziran 

IP address is determined by the core network, and it's beyond the scope of the UE and gNodeB. But I think many core networks have a configuration to specify it.

Best Regards.

**Comment by minziran** [comment]
Thank you very much!
