### ISSUE TITLE
UE sending  Deregistration accept before the smf  unsbscribe from the UDM

### ISSUE THREAD

**Issue by ayoub-tl** [aligungr/UERANSIM#432]
Hello , 
i am confused , the ue is sendign dregestration accept before the smf unsubscribe  unlike  to the 3gpp standard 
![image](https://user-images.githubusercontent.com/68382823/141092743-c51348f5-eca8-4b0a-a66d-841d240a8719.png)

**Comment by namssob** [comment]
Hi @ayoub-tl 
The deregister accept is sent by AMF.
<img width="539" alt="螢幕擷取畫面 2021-11-10 215339" src="https://user-images.githubusercontent.com/3509337/141132762-affc4c26-4a16-423e-b276-9a8703244a3a.png">

According to the spec, AMF can send accept after AM policy terminate. In the mean time, SMF may still handle the clause 5. We can do both clause can do parallel.
