### ISSUE TITLE
NSSAI (SD) in the NG setup doesnt match the one used in the Registration request

### ISSUE THREAD

**Issue by ayoub-tl** [aligungr/UERANSIM#433]
Hi i am having some trouble , 
the UE and gnb are configured with sst 01 and SSD 010203 which can be seen in the ng setup request and response 
But when it come ti registration request/response or pdu seestion establishment it uses a different SD 
can someone help and confirm if it is in fact  a problem on the software, or I am missing something ?
![image](https://user-images.githubusercontent.com/68382823/141097298-5874b6d3-65b0-43bc-b4d9-291ba690db17.png)
![image](https://user-images.githubusercontent.com/68382823/141097395-c6c40704-1d87-44bd-a67b-8964590a1446.png)
![image](https://user-images.githubusercontent.com/68382823/141097058-a255a4f6-ad5a-426c-b0ec-c26dc257036d.png)
![image](https://user-images.githubusercontent.com/68382823/141097176-b00941e7-7b31-470e-a400-7e31bb2542ee.png)
![image](https://user-images.githubusercontent.com/68382823/141096826-bec1a12f-ecfc-4def-b4f3-ab6713d71e18.png)

**Comment by aligungr** [comment]
Hi @ayoub-tl Probably the configuration files are incorrect. Please send your UE and gNodeB config files.

**Comment by ayoub-tl** [comment]
hi @aligungr  here's my configuration files 
free5gc-gnb.yaml 
mcc: '208'          # Mobile Country Code value
mnc: '93'          # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 172.22.0.23   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.22.0.23   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 172.22.0.23    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 10.0.174.97
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 0x010203

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

==================================================
free5gc-ue.yaml
# IMSI number of the UE. IMSI = [208|93|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-208930000000025'
# Mobile Country Code value of HPLMN
mcc: '208'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '93'

# Permanent subscription key
key: '8baf473f2f8fd09487cccbd7097c6862'
# Operator code (OP or OPC) of the UE
op: '8e27b6af0e692e750f32667a3b14605d'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 172.22.0.23

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 0x01
      sd: 0x010203
    emergency: false
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 0x01
    sd: 0x010203

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

**Comment by ayoub-tl** [comment]
Hi @aligungr  , free5gc noted that 66051 is decimal, and it equals to heximal 010203. I want to ask if this a normal behavior ?

**Comment by aligungr** [comment]
@ayoub-tl Yes this is normal behavior. In wireshark it's sometimes written as decimal and sometimes hex. But the real value sent by the nodes are the same. There is no problem in your case, just ignore the Wireshark's notation.
