### ISSUE TITLE
Requested NSSAI doesnt appear  Initial UE message/Registration Request

### ISSUE THREAD

**Issue by ayoub-tl** [aligungr/UERANSIM#434]
expectation
![image](https://user-images.githubusercontent.com/68382823/141119802-9daa372c-3904-44aa-b444-44dd22d5ea69.png)
message captured 
![image](https://user-images.githubusercontent.com/68382823/141119950-de6b8ee4-4897-4266-8f40-d015b3c00f86.png)

**Comment by aligungr** [comment]
@ayoub-tl 

Probably the configuration files are incorrect. Please send your UE and gNodeB config files.

---

And note that Requested NSSAI is **dynamically determined by the UE at runtime** by a relatively complex procedure. And it's not certain ahead of time, and it's not directly read from the config files.

Please see `ue/nas/mm/slice.cpp`

**Comment by ayoub-tl** [comment]
hi @aligungr here's my configuration files
free5gc-gnb.yaml
mcc: '208' # Mobile Country Code value
mnc: '93' # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010' # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

linkIp: 172.22.0.23 # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.22.0.23 # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 172.22.0.23 # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:

address: 10.0.174.97
port: 38412
# List of supported S-NSSAIs by this gNB
slices:

sst: 1
sd: 0x010203
# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

==================================================
free5gc-ue.yaml
# IMSI number of the UE. IMSI = [208|93|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-208930000000025'
# Mobile Country Code value of HPLMN
mcc: '208'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '93'

# Permanent subscription key
key: '8baf473f2f8fd09487cccbd7097c6862'
# Operator code (OP or OPC) of the UE
op: '8e27b6af0e692e750f32667a3b14605d'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:

172.22.0.23
# Initial PDU sessions to be established
sessions:

type: 'IPv4'
apn: 'internet'
slice:
sst: 0x01
sd: 0x010203
emergency: false
uacAic:
mps: false
mcs: false
# UAC Access Control Class
uacAcc:
normalClass: 0
class11: false
class12: false
class13: false
class14: false
class15: false

# Configured NSSAI for this UE by HPLMN
configured-nssai:

sst: 0x01
sd: 0x010203
# Default Configured NSSAI for this UE
default-nssai:

sst: 1
sd: 1
# Supported encryption algorithms by this UE
integrity:
IA1: true
IA2: true
IA3: true

# Supported integrity algorithms by this UE
ciphering:
EA1: true
EA2: true
EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
uplink: 'full'
downlink: 'full'

**Comment by ayoub-tl** [comment]
hi @aligungr  here's my configuration files 

=====================================
free5gc-gnb.yaml 
mcc: '208'          # Mobile Country Code value
mnc: '93'          # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 172.22.0.23   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 172.22.0.23   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 172.22.0.23    # gNB's local IP address for N3 Interface (Usually same with local IP)

\# List of AMF address information
amfConfigs:
  - address: 10.0.174.97
    port: 38412

\# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 0x010203

\# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

==================================================
free5gc-ue.yaml
\# IMSI number of the UE. IMSI = [208|93|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-208930000000025'
\# Mobile Country Code value of HPLMN
mcc: '208'
\# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '93'

\# Permanent subscription key
key: '8baf473f2f8fd09487cccbd7097c6862'
\# Operator code (OP or OPC) of the UE
op: '8e27b6af0e692e750f32667a3b14605d'
\# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
\# Authentication Management Field (AMF) value
amf: '8000'
\# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
\# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

\# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 172.22.0.23

\# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 0x01
      sd: 0x010203
    emergency: false
uacAic:
  mps: false
  mcs: false

\# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

\# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 0x01
    sd: 0x010203

\# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

\# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

\# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

\# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

**Comment by jssidhu94** [comment]
hi @aligungr @ayoub-tl 

Is this issue closed? As I am also not getting requested NSSAI in Wireshark capture. I am using the OAI 5GC for testing. 

@aligungr If its not reading the from provided config file, is there a way, it can be showed in the Wireshark capture ?

**Comment by aligungr** [comment]
@jssidhu94 Requested NSSAI is not included in some cases. This one might be your case. Please see 24.501 for the usage of Requested NSSAI.

**Comment by kanchan8317pandey** [comment]
![Screenshot from 2024-08-26 18-30-10](https://github.com/user-attachments/assets/15bf5174-055a-401d-b47d-926baa6d0e3d)
in the highlited part  i want to know what is 1a and 19. please decripte it in asn.1 as PER encoding rule for nas-pdu in ngap protocol.
