### ISSUE TITLE
How to delete duplicated UE

### ISSUE THREAD

**Issue by ianchen0119** [aligungr/UERANSIM#451]
![image](https://user-images.githubusercontent.com/42661015/144461560-af18a0cc-573c-47df-8550-1bd6fa28a1e1.png)

When I use `nr-cli --dump` to check the device list, I found several UEs have the same IMSI.
I guess this situation is due to I hadn't deregistered UE correctly before I terminated UERANSIM.
Would you have any suggestions for a solution to this issue?

Thanks.

**Comment by aligungr** [comment]
Actually you don't need to deregister the UEs before terminating the program. You can directly kill the processes. In your case perhaps some of the UE processes are remained open?

**Comment by ianchen0119** [comment]
This method works to my question,
Thanks for your fast reply!
