### ISSUE TITLE
UE Registration fails with error: Authentication failure due to SQN out of range

### ISSUE THREAD

**Issue by Mariakhanmm92** [aligungr/UERANSIM#475]
Hello @aligungr!

While connecting 5GC of Amarisoft callbox with UERANSIM, I encountered this issue. The gNB of UERANSIM can successfully connect with the 5GC, however when I run the UE simulator program, it indicates the errors, which can be seen in the following picture.

![ue](https://user-images.githubusercontent.com/57102216/149496297-a9c0e3b8-cdba-4942-ada2-d5f3de7446d3.png)

The gNB terminal looks like below attached picture;

![gNB](https://user-images.githubusercontent.com/57102216/149497193-b0be7b33-980f-4135-937e-9296c11c83ff.png)

However, 5GC shows the connected gNB and UE context

![5GC at amaricallbox](https://user-images.githubusercontent.com/57102216/149496870-420f22e1-8695-441e-b403-4feb9c1b91bd.png)

Could you please suggest something to resolve this issue?

Thanks and BR,
Maria Majid

**Comment by aligungr** [comment]
Hi @Mariakhanmm92 

Make sure that authentication parameters in UE config file matches with core network side such as `key`, `op` and others.

Best.

**Comment by Mariakhanmm92** [comment]
Hi @aligungr 

I rechecked the parameters at both sides and everything seems fine to me. 

following are the configuration at UE side;

[UERAN UE.txt](https://github.com/aligungr/UERANSIM/files/7903990/UERAN.UE.txt)

following are the configurations at 5GC by Amarisoft

ue_db: [{
    sim_algo: "xor", /* USIM authentication algorithm: xor, milenage or tuak */
    imsi: "001010123456789", 
    amf: 0x9001, /* Authentication Management Field */
    sqn: "000000000000", /* Sequence Number */
    K: "00112233445566778899aabbccddeeff", 
    opc: "E8ED289DEBA952E4283B54E88E6183CA",

    impi: "001010123456789@ims.mnc001.mcc001.3gppnetwork.org",
    impu: ["001010123456789", "tel:0600000000", "tel:600"],
    domain: "ims.mnc001.mcc001.3gppnetwork.org",
    multi_sim: true, /* Experimental */
   }]

  /* NAS ciphering algorithm preference. EEA0 is always the last. */
  nas_cipher_algo_pref: [ 2, 1 ], /*1: EEA1 (Snow 3G), 2: EEA2 (128 bit AES), 3: EEA3 (ZUC)*/
  /* NAS integrity algorithm preference. EIA0 is always the last. */
  nas_integ_algo_pref: [ 2, 1 ], /* 1: EIA1 (Snow 3G), 2: EIA2 (128 bit AES), 3: EIA3 (ZUC)*/

BR,
Maria Majid

**Comment by aligungr** [comment]
Hi @Mariakhanmm92 

I think sim_algo seems incorrect, it should be **milenage** instead of xor.

**Comment by Mariakhanmm92** [comment]
Hi @aligungr 

Great thanks for the correction. I changed it to milenage, and Its working perfectly fine now.

BR,
Maria Majid
