### ISSUE TITLE
[ERRO][SMF][CTX] In ActivateUpLinkTunnel UPF IP:  127.0.0.8 ; [ERRO][SMF][CTX] Allocate PDR Error:  this upf do not associate with smf

### ISSUE THREAD

**Issue by JoseVOliveria** [aligungr/UERANSIM#476]
VM1 IP (free5gc): 192.168.99.101
VM2 Ip (UERANSIM): 192.168.99.102

I get the following error when i connect the UE. I Think it cant estlablish a PDU session.:

![error](https://user-images.githubusercontent.com/70780582/149636372-49ffecff-4704-4b3a-8499-93be4cb19927.png)

However i think i have correctly configured the config files:

![smfcfg yaml](https://user-images.githubusercontent.com/70780582/149636373-cf1fa3f5-8045-4a9d-a0c7-b6e3d7ef0ac3.png)

**Comment by sajidkhan2067** [comment]
I am facing the same problem. How did you solve it?

**Comment by sajidkhan2067** [comment]
> I am facing the same problem. How did you solve it?

@JoseVOliveria can you please help me in that regards?

**Comment by sajidkhan2067** [comment]
As the issue is closed, I think you got a solution.
