### ISSUE TITLE
How to send the req without SD of S-NSSAI

### ISSUE THREAD

**Issue by ianchen0119** [aligungr/UERANSIM#479]
The clause 28.4.1 of 3GPP TS 23.003:
> A Slice Differentiator (SD), which is optional information that complements the Slice/Service type(s) to differentiate amongst multiple Network Slices.

Could you help me to know How to set SD as no value in both ue config file & gnB config file?

Thanks a lot.

**Comment by aligungr** [comment]
You can simply delete the SD fields or you can assign `null` to these fields.

For example, before:
```
sst: 1,
sd: 1
```

after:
```
sst: 1
# Here we deleted the SD line
```

etc.

**Comment by ianchen0119** [comment]
Thanks for your fast reply.
Moreover, I suppose if I assign the SD value as null, the SD of sent message will be set as the reserved value, that's defined in 3GPP spec.
![image](https://user-images.githubusercontent.com/42661015/151354748-d2e2aba5-5deb-47a9-925d-7dff80d12c76.jpeg)
Please help to advise if you have any comment,
Thanks again.

**Comment by aligungr** [comment]
@ianchen0119 

I could not understand what did you exactly mean. Could you clarify more?

**Comment by ianchen0119** [comment]
@aligungr 
According to the Clause 28.4.2 of 3GPP 23.003:
> The SD field has a reserved value "no SD value associated with the SST" defined as hexadecimal FFFFFF

Thus, when I delete the SD value in config file or assign `null` to the SD field, the expected behavior is:
UERANSIM will send `SD = 0xFFFFFF` within Registration Request.

I'm wondering if UERANSIM has implemented this feature?
If No, maybe I can assign `0xFFFFFF` to the SD field in the config file by myself?

**Comment by ianchen0119** [comment]
@aligungr 

Noted and thanks for your kindly help!
Wish you have a nice day.
