### ISSUE TITLE
[Question] not able to capture radio requests 

### ISSUE THREAD

**Issue by ayoub-tl** [aligungr/UERANSIM#494]
hello @aligungr i am unable to see rrc setup request which is given by UE to gnb during initial 5G registration. is rrc procedure not implemented in UERANSIM
and can i captur mac nr /pdcp/ rlc  ???
Thank you

**Comment by aligungr** [comment]
Hello @ayoub-tl 

UERANSIM does **not** implement 5G radio protocols below the RRC layer. And 5G radio is **partially simulated over UDP** as specified in the documentations. So, PHY, MAC, RLC, PDCP is not implemented in UERANSIM. However you can capture some RRC messages.

Please see the following Wireshark plugin:
https://github.com/louisroyer/RLS-wireshark-dissector

**Comment by ayoub-tl** [comment]
Thanks for the response @aligungr
