### ISSUE TITLE
NAS security does not include in Deregister request when using NIA2 as cyber algorithm

### ISSUE THREAD

**Issue by namssob** [aligungr/UERANSIM#502]
Environment: 
- Core: free5gc v3.0.6
- UeRansim: v3.2.6

When we use NIA2 as NAS security, the deregister request will not include NAS security. 

![Screenshot 2022-03-18 121014](https://user-images.githubusercontent.com/3509337/158936640-79fec005-c710-41d8-91cf-2a94db39584c.png)
 
![Screenshot 2022-03-18 120954](https://user-images.githubusercontent.com/3509337/158936626-b67f7e00-ea05-4fc3-8468-06a5c868ffac.png)

pcap:
[free5gc.zip](https://github.com/aligungr/UERANSIM/files/8301525/free5gc.zip)

**Comment by aligungr** [comment]
Hi @namssob 

I think I don't fully understand your question.
However, UERANSIM always skips the ciphering in UE-originated De-registration Request messages.

Best.

**Comment by namssob** [comment]
Hi @aligungr , 
I misunderstood the spec before; yes the deregister message should not be cyphered, but I found that the security header in the deregister message is "integrity protected and ciphered". It should not be correct here. Suggest changing it to "integrity"
![image (1)](https://user-images.githubusercontent.com/3509337/160032252-1a4ac80d-fb92-41c5-8d15-47398e28f5af.png)

**Comment by namssob** [comment]
Hi @aligungr and @ss920386, 
Yes, this PR is fixed as expected.

UE will send the NAS Deregister with NAS Security when UE is in cm-connect. 
![CM_Connect](https://user-images.githubusercontent.com/3509337/160515240-430ede18-3865-4b86-9a14-f4c06cc7c05c.png)

UE will send the NAS Deregister with Plain when UE is in cm-idle. 
![CM_IDLE](https://user-images.githubusercontent.com/3509337/160515034-3e68c641-2b33-4015-86c3-8f10c6e86c57.png)
