### ISSUE TITLE
UERANSIM sends encrypted NAS although amf set ciphering algorithm as 5G-EA0

### ISSUE THREAD

**Issue by yg8106** [aligungr/UERANSIM#515]
UERANSIM sends encrypted NAS although amf set ciphering algorithm as 5G-EA0. This is found in playing with free5gc.

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/21269228/165443421-7c369e29-eafb-4223-8896-a081a66bdd83.png">

See attached picture:
1. Frame 183 is SMC with EA0
2. Frame 450 is encrypted NAS (PDU Session Establishment Request).

**Comment by aligungr** [comment]
Hi @yg8106 

This is actually desired behavior. Please see **TS 24.501**.

BR

**Comment by yg8106** [comment]
Thanks. It was mistake on my end - didn't enable EA0 decryption in Wireshark preference.
