### ISSUE TITLE
IPv6 Support for UE on UERANSIM

### ISSUE THREAD

**Issue by panyogesh** [aligungr/UERANSIM#520]
Any plans for supporting UE IPv6

**Comment by panyogesh** [comment]
Have done some  quick local changes and able to proceed. Closing the issue.

**Comment by akihiro272** [comment]
@panyogesh 
Hi, could you share your solution? I wanna use ipv6 for Uplane.

**Comment by yoko164** [comment]
@panyogesh 
Hi, did you find solution for ipv6 Uplane? Could you share it?

**Comment by panyogesh** [comment]
@yoko164 : I did some changes in UERANSIM to send the IPv6 PDU entry and then used scapy to send the IPv6 traffic. This solved my purpose.

**Comment by Marcel2508** [comment]
Hey @panyogesh could you maybe share your modifications? Thanks!
