### ISSUE TITLE
[Question] A valid way to decipher NAS 5GS message (wireshark)

### ISSUE THREAD

**Issue by konradkar2** [aligungr/UERANSIM#558]
I'm trying to inspect the content of NAS messages sent between UE and CN, is there a tool to achieve that?
I suppose this is possible as we have access to the UE subscription profile and CN database.
As 5GC I'm using free5gc.

![pF8myd1](https://user-images.githubusercontent.com/44207253/189089884-2a5a24ce-a0bc-4036-93e7-1db881336e95.png)

Any help is appreciated.

**Comment by s5uishida** [comment]
Hi @konradkar2 

The following URL may be helpful for you?

https://open5gs.org/open5gs/docs/troubleshoot/02-now-in-github-issues/
- Wireshark cannot decode NAS-5GS

**Comment by konradkar2** [comment]
Thank you!
In case your link goes down:
In Wireshark go to preferences -> Protocols -> NAS-5GS -> check the box "Try to detect and decode 5G-EA0 ciphered message" - not sure how much traffic you need for that, but for me, it works.
