### ISSUE TITLE
Ping not working

### ISSUE THREAD

**Issue by MaFe1401** [aligungr/UERANSIM#562]
Hi! I need to know why is that I can ping by using nr-binder:
![nrbinder](https://user-images.githubusercontent.com/57569408/192863449-9c29664b-d428-4790-a178-779b6271b960.png)

But manually binding to uesimtun0 does not work:
![uesimtun0](https://user-images.githubusercontent.com/57569408/192864164-1d54690f-e9e1-4552-9561-679c85bee05f.png)

Using wireshark it can be seen that the ping request does not receive any response:
![ping](https://user-images.githubusercontent.com/57569408/192864522-239eb1d4-12c9-47fc-a9b0-45b3a9250e23.png)

Thanks in advance!

**Comment by lilyhuegerich** [comment]
Hi I had the same problem, what worked for me was to separate into 2 vms (probably not necessary but makes overview easier) as well as these commands in the Core VM:

sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE

from this tutorial:
https://medium.com/rahasak/5g-core-network-setup-with-open5gs-and-ueransim-cd0e77025fd7

good luck :)

**Comment by MaFe1401** [comment]
Thank you so much @lilyhuegerich, that worked :)
