### ISSUE TITLE
Can't able to capture RRC packets in wireshark.

### ISSUE THREAD

**Issue by devopsTamil** [aligungr/UERANSIM#589]
Hi Team, #588 

I use VMs (VirtualBox) for UERANSIM. OS installed in it is Ubuntu 20.04. 2GB Memory, 2vCPU.

After running gNodeB yml file `nr-gnb -c ../config/custom-gnb.yaml` I got below output.

![image](https://user-images.githubusercontent.com/113607316/208609099-d59acfdf-2fab-4681-b0dd-5522581e7839.png)

And also while I'm running UE yml file `nr-ue -c ../config/custom-ue.yaml` I got below output.

![image](https://user-images.githubusercontent.com/113607316/208609449-7f056915-c79d-4ff6-8380-af8cf8a23b14.png)

After running this two commands I can see that `UE` and `gNodeB` are updated in **5gc webconsole** and they are clearly mentioning in the terminal too.
![image](https://user-images.githubusercontent.com/113607316/208626234-696ca7b9-5e43-415c-a13a-01c80f599ce6.png)
![image](https://user-images.githubusercontent.com/113607316/208626298-e159c2ad-9e54-498a-98f9-de8137e4f4d8.png)

But I can't capture those `RRC-Packets` in wireshark.

![image](https://user-images.githubusercontent.com/113607316/208626949-d6fc428f-4569-4767-ac08-1bfd60a2e7de.png)

 Expecting response from anyone. Need your attention @aligungr or one of your team.

Thanks in advance,
Tamilvanan

**Comment by s5uishida** [comment]
You can use the following in Wireshark.
```
UERANSIM/tools/rls-wireshark-dissector.lua
```

**Comment by devopsTamil** [comment]
> You can use the following in Wireshark.
> 
> ```
> UERANSIM/tools/rls-wireshark-dissector.lua
> ```

Can you please elaborate this. I can't get it properly @s5uishida 

Thanks in advance
Tamilvanan

**Comment by devopsTamil** [comment]
Team, please I need some attention here.
@aligungr

**Comment by s5uishida** [comment]
https://www.wireshark.org/docs/wsug_html_chunked/ChPluginFolders.html

**Comment by devopsTamil** [comment]
Hi @s5uishida ,
I placed the `rls.lua` file in `~/.local/lib/wireshark/plugins`  (PFA)

![image](https://user-images.githubusercontent.com/113607316/209509403-b9e80341-3cff-4d70-a438-8ffecde043ea.png)

Also already the `rls-wireshark-dissector.lua` plugin is present in `UERANSIM/tools/`  (PFA)

![image](https://user-images.githubusercontent.com/113607316/209509633-0f13f49a-d188-4234-aa5e-feca057a1d00.png)

But while capturing the packets in wireshark, it shows empty in `rrc-filter`  (PFA)

![image](https://user-images.githubusercontent.com/113607316/209509733-e26ede2c-3d74-47b2-a038-69ea261136c4.png)


Correct me if I'm wrong. Thanks is advance.
Tamilvanan

**Comment by s5uishida** [comment]
Where did you get the `rls.lua` file placed in `~/.local/lib/wireshark/plugins`?

**Comment by devopsTamil** [comment]
@s5uishida 

https://github.com/louisroyer/RLS-wireshark-dissector

From the above github repository.

![image](https://user-images.githubusercontent.com/113607316/209535078-197fd40f-e816-46c8-8ad5-2f5f23ada2bd.png)


Correct me if I'm wrong. Thanks is advance.
Tamilvanan

**Comment by s5uishida** [comment]
In that case the filter is `rls-3.2`. On the other hand, for `UERANSIM/tools/rls-wireshark-dissector.lua` the filter is `rls`.

**Comment by devopsTamil** [comment]
I am very happy to get quick replies from you,
Now coming to the point.
I executed the wireshark and runned the `gNB.yaml file` first and running `UE.yaml file` second in `UERANSIM virtual machine`. After a while, it seems that there is no packets captured for filters `rls` , `rls-3.1` , `rls-3.2`.  (PFA)

![image](https://user-images.githubusercontent.com/113607316/209541195-1381a9b7-ad17-47d7-91cf-120746ebdc39.png)

![image](https://user-images.githubusercontent.com/113607316/209541395-d34d5faa-0e7e-457f-895f-8d3017a4ba20.png)


I don't know where I'm missing things. Again need your help @s5uishida !!

Thanks in advance
Tamilvanan

**Comment by s5uishida** [comment]
With wireshark, how about reading the pcap file created by running `tcpdump` on the gNodeB machine?

**Comment by devopsTamil** [comment]
I've tried that way too. `ie., reading the pcap file in wireshark that is captured using tcp-dump` . But still RRC messages are not coming there.

**Comment by s5uishida** [comment]
Read my pcap file with wireshark and try to check RLS/RRC.

[ueransim_gnodeb.zip](https://github.com/aligungr/UERANSIM/files/10303379/ueransim_gnodeb.zip)

Sorry, I cannot support you any further.
