### ISSUE TITLE
RRC messages doesn't show in wireshark

### ISSUE THREAD

**Issue by devopsTamil** [aligungr/UERANSIM#591]
Hi Team, Hope u r doing good. #275 

@aligungr
@p3ngdump 
@iman432 
@louisroyer  
@sahusonali25 

After using the plugin in `UERANSIM/tools/rls-wireshark-dissector.lua` , it shows empty for `RRC` .

![image](https://user-images.githubusercontent.com/113607316/209770339-a12acd78-fedd-45ed-bd75-9214c01882ea.png)

Can you guys please help me with this RLS Plugin `RRC Messages capture` .

Thanks in advance
Tamilvanan

**Comment by louisroyer** [comment]
Use the filter `nr-rrc` instead of `rrc`.

**Comment by devopsTamil** [comment]
Hi @louisroyer , Thank you so much for you precious time.

Actually, I tried using `nr-rrc` also. But no packets there @louisroyer 

![image](https://user-images.githubusercontent.com/113607316/209905044-c75e2fca-9fc5-4d7f-b15c-30649d223909.png)

Is there any other ways to get `RRC in wireshark` .

Thanks in advance
Tamilvanan

**Comment by devopsTamil** [comment]
Hi @louisroyer need u r help on this.

**Comment by louisroyer** [comment]
Can you send a pcap and your Wireshark exact version ? I cant reproduce it without it…
Also, you can try to open [these pcaps](https://github.com/louisroyer/RLS-wireshark-dissector/tree/master/pcap). They contain some nr-rrc. If you are able to see them, there is something wrong with your capture, and if you are not able to see them, there is something wrong with your plugin installation.

**Comment by devopsTamil** [comment]
But also in [these pcaps](https://github.com/louisroyer/RLS-wireshark-dissector/tree/master/pcap) also I can't see any `nr-rrc` 

![image](https://user-images.githubusercontent.com/113607316/210259440-430b8ce8-0950-4969-8d13-a6c4a775fd7e.png)

Also I'm attaching my capture files. And I'll be waiting for your response.

[Wireshark PCAP files.zip](https://github.com/aligungr/UERANSIM/files/10332701/Wireshark.PCAP.files.zip)


Thanks in advance,
Tamilvanan

**Comment by louisroyer** [comment]
Your pcap is correct and I can see `nr-rrc` in it, so this is definitely an issue with your Wireshark version or with your installation of the plugin.
1. What version of Wireshark are your using? It must be 3.0.0 at least (`nr-rrc` is not implemented in older versions).
2. Check your plugin is well loaded (go to `Help` > `About Wireshark` > `Plugins`, and check the presence of a `rls-wireshark-dissector.lua` line (in the image below, I have `rls.lua`).
![2023-01-02T18:02:07,143671209+01:00](https://user-images.githubusercontent.com/55180044/210260914-33bea767-103e-4462-aaf2-45f763647598.png)
3. If the plugin is not loaded, it is probably installed in the wrong folder. Depending on your OS, the  Lua Plugins folder may not be the same, you may check it in `Help`> `About Wireshark` > `Folder`. You need to reload lua plugins after the installation (`Anazyse` > `Reload Lua Plugins`, or restart Wireshark).
![2023-01-02T18:04:37,315190234+01:00](https://user-images.githubusercontent.com/55180044/210261192-ac2b32d3-e306-4bb0-8294-f27ad7414877.png)
4. You can also try to follow instructions of [this README](https://github.com/louisroyer/RLS-wireshark-dissector), it may be easier to install.

**Comment by devopsTamil** [comment]
Hi @louisroyer ,
**Thank you so much for your valuable time with my issues.**

Actually I have installed wireshark version `4.0.2`

![image](https://user-images.githubusercontent.com/113607316/210349782-c562c139-e842-4296-b036-b6f951703893.png)


Then, I have configured my wireshark plugins to the directory as you showed in the above picture.
`rls-3-1.lua` - `/usr/lib/x86_64-linux-gnu/wireshark/plugins/rls/protocol/rls-3-1.lua`
`rls-3-2.lua` - `/usr/lib/x86_64-linux-gnu/wireshark/plugins/rls/protocol/rls-3-2.lua`
`   rls.lua   ` - `/usr/lib/x86_64-linux-gnu/wireshark/plugins/rls/rls.lua`

![image](https://user-images.githubusercontent.com/113607316/210350242-670d00f8-6339-408a-bf4e-face5c44548e.png)



And plugins folders,

![image](https://user-images.githubusercontent.com/113607316/210350352-c7c5751f-8429-4987-a5f0-f090dfcbcaa8.png)


But even though, the `nr-rrc` and `rrc` packets are not visible.

![image](https://user-images.githubusercontent.com/113607316/210350534-75798164-cf61-469f-86e3-06e44e9f3860.png)

![image](https://user-images.githubusercontent.com/113607316/210350654-ed34503d-7a43-49f0-974c-15d8bacb7c55.png)


I think only you can help me with this. And I'll be waiting your next reply on this.

Thanks in advance,
Tamilvanan

**Comment by devopsTamil** [comment]
Hi @louisroyer ,
Thank you so much for your valuable time with my issues.

I have captured a very fresh PCAP file now, sharing it with you. And please ignore the above files I've shared.

[ueransim-latest-capture-2023-04-01.zip](https://github.com/aligungr/UERANSIM/files/10341667/ueransim-latest-capture-2023-04-01.zip)


Can you please spend a couple of minute to check whether `nr-rrc` or `rrc` or `udp.port==4997` is working or not.

Also I configured the plugins with directory and attached the Screenshot below.

![image](https://user-images.githubusercontent.com/113607316/210490545-c70af914-8e27-4a92-a6b0-b564dcf503c3.png)

![image](https://user-images.githubusercontent.com/113607316/210490570-a8dfb8f6-57fd-474e-b5d8-2440e00f73d8.png)

The version of wireshark is `4.0.2 (Git v4.0.2 packaged as 4.0.2-1)`

![image](https://user-images.githubusercontent.com/113607316/210490670-0338b247-e894-47c3-bb06-c4a8b9aaa54b.png)


I'll be waiting your next reply on this.

Thanks in advance,
Tamilvanan

**Comment by louisroyer** [comment]
This file doesn’t contain any `nr-rrc` because you captured the interface between the gNB and the AMF instead of the interface between the UE and the gNB.

**Comment by devopsTamil** [comment]
Yeah, you are absolutely right @louisroyer ,

As of now, I deployed `5G core` in one local virtual machine and `UERANSIM` in another local virtual machine.
So, thereby I configured those two using `NAT network IP` . After that I used to check running status of 5G core web console and start the wireshark in NAT network adapter which is `enp0s3` configured in my machine. Then at last, in UERANSIM, I will run gNodeB yaml file and UE yaml file.

Is there any other ways to run gNodeB and UE in different machines. So that we can trace the connections between them seperately. @louisroyer 

I'll be waiting your next reply on this.

Thanks in advance,
Tamilvanan

**Comment by louisroyer** [comment]
There is nothing preventing you from using different machines/VMs for gNB and UEs. You just have to edit UERANSIM config files to use something different from `127.0.0.1` for `linkIp`/`gnbSearchList`. But you can also just install `tcpdump` inside your UERANSIM VM and retrieve traffic on your host using Wireshark’s `sshdump` for example, or directly install Wireshark/Tshark  inside your UERANSIM VM.

**Comment by devopsTamil** [comment]
Yeah It's working for me now @louisroyer .

Thank you so much for your time and very quick responses with my issues.

**Comment by devopsTamil** [comment]
yeah, you're right @warlock1302 . we need to create two different vm's to achieve it.
