### ISSUE TITLE
[error] Initial Registration failed [SEMANTICALLY_INCORRECT_MESSAGE]

### ISSUE THREAD

**Issue by pedrovianadias** [aligungr/UERANSIM#647]
Hello everyone, everything alright ?

While registering UE to Open5Gs, I am getting the following errors, can you help me with this problem ?
[Initial Registration Failed [Semantically Incorrect Message].zip](https://github.com/aligungr/UERANSIM/files/11605155/Initial.Registration.Failed.Semantically.Incorrect.Message.zip)

ubuntu@ubuntu:~/UERANSIM/config$ ../build/nr-ue -c ue1.yaml
UERANSIM v3.1.0
[2023-05-30 18:19:38.201] [nas] [debug] NAS layer started
[2023-05-30 18:19:38.201] [rrc] [debug] RRC layer started
[2023-05-30 18:19:38.201] [nas] [info] UE switches to state: MM-DEREGISTERED/PLMN-SEARCH
[2023-05-30 18:19:38.202] [nas] [info] UE connected to gNB
[2023-05-30 18:19:38.202] [nas] [info] UE switches to state: MM-DEREGISTERED/NORMAL-SERVICE
[2023-05-30 18:19:38.202] [nas] [info] UE switches to state: MM-REGISTERED-INITIATED/NA
[2023-05-30 18:19:38.202] [rrc] [debug] Sending RRC Setup Request
[2023-05-30 18:19:38.203] [rrc] [info] RRC connection established
[2023-05-30 18:19:38.203] [nas] [info] UE switches to state: CM-CONNECTED
**[2023-05-30 18:19:38.204] [nas] [error] Initial Registration failed [SEMANTICALLY_INCORRECT_MESSAGE]
[2023-05-30 18:19:38.204] [nas] [error] Registration rejected with unhandled MMCause: SEMANTICALLY_INCORRECT_MESSAGE_****
[2023-05-30 18:19:38.204] [nas] [info] UE switches to state: MM-DEREGISTERED/NA
[2023-05-30 18:19:38.204] [nas] [info] UE switches to state: MM-DEREGISTERED/NORMAL-SERVICE
[2023-05-30 18:19:38.204] [nas] [info] UE switches to state: MM-REGISTERED-INITIATED/NA

ubuntu@ubuntu:~/UERANSIM/config$ ../build/nr-gnb -c gnb1.yaml
UERANSIM v3.1.0
[2023-05-30 18:13:40.758] [sctp] [info] Trying to establish SCTP connection... (127.0.0.5:38412)
[2023-05-30 18:13:40.760] [sctp] [info] SCTP connection established (127.0.0.5:38412)
[2023-05-30 18:13:40.760] [sctp] [debug] SCTP association setup ascId[37559]
[2023-05-30 18:13:40.760] [ngap] [debug] Sending NG Setup Request
[2023-05-30 18:13:40.761] [ngap] [debug] NG Setup Response received
[2023-05-30 18:13:40.761] [ngap] [info] NG Setup procedure is successful
[2023-05-30 18:19:38.202] [mr] [info] New UE connected to gNB. Total number of UEs is now: 1
[2023-05-30 18:19:38.202] [rrc] [debug] Sending RRC Setup for UE[3]
[2023-05-30 18:19:38.203] [ngap] [debug] Initial NAS message received from UE 3
[2023-05-30 18:19:38.204] [ngap] [debug] UE Context Release Command received
**[2023-05-30 18:19:38.204] [ngap] [error] UE context not found with id: 3**

ubuntu@ubuntu:~$ sudo service open5gs-amfd status

05/30 18:13:40.760: [amf] INFO: gNB-N2 accepted[127.0.0.100]:50423 in ng-path module (../src/amf/ngap-sctp.c:113)
05/30 18:13:40.760: [amf] INFO: gNB-N2 accepted[127.0.0.100] in master_sm module (../src/amf/amf-sm.c:741)
05/30 18:13:40.760: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:1178)
05/30 18:13:40.761: [amf] INFO: gNB-N2[127.0.0.100] max_num_of_ostreams : 10 (../src/amf/amf-sm.c:780)
05/30 18:19:38.203: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:372)
05/30 18:19:38.203: [amf] INFO: [Added] Number of gNB-UEs is now 1 (../src/amf/context.c:2502)
05/30 18:19:38.203: [amf] INFO:     RAN_UE_NGAP_ID[1] AMF_UE_NGAP_ID[3] TAC[1] CellID[0x10] (../src/amf/ngap-handler.c:533)
05/30 18:19:38.203: [amf] INFO: [suci-0-999-70-0000-0-0-0000000003] Unknown UE by SUCI (../src/amf/context.c:1776)
05/30 18:19:38.203: [amf] INFO: [Added] Number of AMF-UEs is now 1 (../src/amf/context.c:1563)
05/30 18:19:38.203: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:985)
**05/30 18:19:38.203: [gmm] ERROR: Non cleartext IEs is included [0x8000e] (../src/amf/gmm-handler.c:116)**
05/30 18:19:38.203: [gmm] ERROR: Unknown reg_type[0] (../src/amf/gmm-sm.c:1004)
05/30 18:19:38.203: [gmm] ERROR: gmm_handle_registration_request() failed [95] (../src/amf/gmm-sm.c:1008)
05/30 18:19:38.204: [amf] ERROR: Unknown reg_type[0] (../src/amf/nas-path.c:215)
05/30 18:19:38.204: [amf] WARNING: [(null)] Registration reject [95] (../src/amf/nas-path.c:219)
05/30 18:19:38.204: [amf] INFO: UE Context Release [Action:3] (../src/amf/ngap-handler.c:1632)
05/30 18:19:38.204: [amf] INFO:     RAN_UE_NGAP_ID[1] AMF_UE_NGAP_ID[3] (../src/amf/ngap-handler.c:1633)
05/30 18:19:38.204: [amf] INFO:     SUCI[Unknown] (../src/amf/ngap-handler.c:1636)
05/30 18:19:38.204: [amf] INFO: [Removed] Number of gNB-UEs is now 0 (../src/amf/context.c:2509)
05/30 18:19:38.204: [amf] INFO: [Removed] Number of AMF-UEs is now 0 (../src/amf/context.c:1656)

Below are some of the configuration of my VM

gNb

mcc: '999'          # Mobile Country Code value
mnc: '70'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 127.0.0.101   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 127.0.0.100   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 127.0.0.200  # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 127.0.0.5
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

UE

# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-999700000000003'
# Mobile Country Code value
mcc: '999'
# Mobile Network Code value (2 or 3 digits)
mnc: '70'

# Permanent subscription key
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
# Operator code (OP or OPC) of the UE
op: 'E8ED289DEBA952E4283B54E88E6183CA'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 127.0.0.101

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 1
      

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1
    sd: 1
    
# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

# List of requested S-NSSAIs by this UE
slices:
  - sst: 1
    sd: 1

# Supported encryption and integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true
ciphering:
  EA1: true
  EA2: true
  EA3: true

AMF

amf:
    sbi:
      - addr: 127.0.0.5
        port: 7777
    ngap:
      - addr: 127.0.0.5
    metrics:
      - addr: 127.0.0.5
        port: 9090
    guami:
      - plmn_id:
          mcc: 999
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 999
          mnc: 70
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 999
          mnc: 70
        s_nssai:
          - sst: 1
            sd: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

![image](https://github.com/aligungr/UERANSIM/assets/134971179/29622e02-7fc5-4ae9-ae11-5de3b590a72c)

Thanks in advance for the help

**Comment by SanzidaH** [comment]
Hi pedrovianadias, I am facing similar issue. Could you please share if you could solve it and how it can be fixed?

**Comment by pedrovianadias** [comment]
> Hi pedrovianadias, I am facing similar issue. Could you please share if you could solve it and how it can be fixed?

Hello SanzidaH, how are you ? 

From what I remember, ueransim was not in the most up to date version, so I just installed ueransim again in the most up to date version and it worked.

I hope it helped you

**Comment by SanzidaH** [comment]
> > Hi pedrovianadias, I am facing similar issue. Could you please share if you could solve it and how it can be fixed?
> 
> Hello SanzidaH, how are you ?
> 
> From what I remember, ueransim was not in the most up to date version, so I just installed ueransim again in the most up to date version and it worked.
> 
> I hope it helped you

Thank you for your response, pedrovianadias. I hope you are doing well too. It was the same case for me as well!
