### ISSUE TITLE
After downloading, compile and install, an error occurs

### ISSUE THREAD

**Issue by honysyang** [aligungr/UERANSIM#674]
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/idle.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/nas.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/sap.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/state.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/sysinfo.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/rrc/task.cpp.o
[ 99%] Building CXX object src/ue/CMakeFiles/ue.dir/timer.cpp.o
[100%] Building CXX object src/ue/CMakeFiles/ue.dir/tun/config.cpp.o
[100%] Building CXX object src/ue/CMakeFiles/ue.dir/tun/task.cpp.o
[100%] Building CXX object src/ue/CMakeFiles/ue.dir/tun/tun.cpp.o
[100%] Building CXX object src/ue/CMakeFiles/ue.dir/types.cpp.o
[100%] Building CXX object src/ue/CMakeFiles/ue.dir/ue.cpp.o
[100%] Linking CXX static library libue.a
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
make[3]: Leaving directory '/home/free5gc/UERANSIM/cmake-build-release'
[100%] Built target ue
make[3]: Entering directory '/home/free5gc/UERANSIM/cmake-build-release'
make[3]: Leaving directory '/home/free5gc/UERANSIM/cmake-build-release'
make[3]: Entering directory '/home/free5gc/UERANSIM/cmake-build-release'
make[3]: Warning: File '/home/free5gc/UERANSIM/src/ue.cpp' has modification time 28329 s in the future
[100%] Building CXX object CMakeFiles/nr-ue.dir/src/ue.cpp.o
/home/free5gc/UERANSIM/src/ue.cpp: In function ‘nr::ue::UeConfig* ReadConfigYaml()’:
/home/free5gc/UERANSIM/src/ue.cpp:164:17: error: ‘struct nr::ue::UeConfig’ has no member named ‘tunPrefix’
  164 |         result->tunPrefix = yaml::GetString(config, "tunPrefix", 1, 12);
      |                 ^~~~~~~~~
/home/free5gc/UERANSIM/src/ue.cpp: In function ‘nr::ue::UeConfig* GetConfigByUe(int)’:
/home/free5gc/UERANSIM/src/ue.cpp:362:8: error: ‘struct nr::ue::UeConfig’ has no member named ‘tunPrefix’
  362 |     c->tunPrefix = g_refConfig->tunPrefix;
      |        ^~~~~~~~~
/home/free5gc/UERANSIM/src/ue.cpp:362:33: error: ‘struct nr::ue::UeConfig’ has no member named ‘tunPrefix’
  362 |     c->tunPrefix = g_refConfig->tunPrefix;
      |                                 ^~~~~~~~~
CMakeFiles/nr-ue.dir/build.make:75: recipe for target 'CMakeFiles/nr-ue.dir/src/ue.cpp.o' failed
make[3]: *** [CMakeFiles/nr-ue.dir/src/ue.cpp.o] Error 1
make[3]: Leaving directory '/home/free5gc/UERANSIM/cmake-build-release'
CMakeFiles/Makefile2:269: recipe for target 'CMakeFiles/nr-ue.dir/all' failed
make[2]: *** [CMakeFiles/nr-ue.dir/all] Error 2
make[2]: Leaving directory '/home/free5gc/UERANSIM/cmake-build-release'
Makefile:90: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/free5gc/UERANSIM/cmake-build-release'
makefile:5: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by aligungr** [comment]
Sorry, that was a minor mistake. Please try again with the latest sources.
