### ISSUE TITLE
Unable to ping 8.8.8.8 from uesimtun interface

### ISSUE THREAD

**Issue by Vinothkumar-sakthivel** [aligungr/UERANSIM#707]
I tried UERANSIM with open5gs, sctp, ngap, rrc,  PDU Session establishment everything successful and uesimtun also created with IP.
But I can't able to ping google.com through uesimtun IP.
Below steps are tired.

Ip route update:
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -I INPUT --source 10.45.0.2/16 -j ACCEPT
sudo iptables -t nat -I POSTROUTING --out-interface ens3 -j MASQUERADE
sudo iptables -I FORWARD --in-interface ens3 --out-interface ogstun -j ACCEPT
sudo iptables -I FORWARD --in-interface ogstun --out-interface ens3 -j ACCEPT

Deployment scenerios:
Scenerio1 : UERANSIM & Open5gs in same VM
Scenerio2 : UERANSIM in one VM and Open5gs  in another VM

Screenshots:
![image](https://github.com/aligungr/UERANSIM/assets/104768892/3f4edb75-d329-4d93-bd6b-edc51ff57b7e)
![image](https://github.com/aligungr/UERANSIM/assets/104768892/3c8a8bc4-8082-4557-952d-a3b903ff6341)
![image](https://github.com/aligungr/UERANSIM/assets/104768892/2584a00a-826f-478f-8546-ac35db3ae793)
![image](https://github.com/aligungr/UERANSIM/assets/104768892/0096d75d-2ebd-4ed7-b59e-a13e15e5277f)

@aligungr : Please suggest

**Comment by Vinothkumar-sakthivel** [comment]
Issue resolved

**Comment by priyanshs** [comment]
@Vinothkumar-sakthivel  what was this issue?

**Comment by tjzvbokbnft** [comment]
Hi, I have met the same issue, can you share with me how did you solve it?
