### ISSUE TITLE
Initial-Registration failed with free5gc

### ISSUE THREAD

**Issue by tim-ywliu** [aligungr/UERANSIM#71]
Hi,

After testing with free5gc, I found an issue.
From free5gc log, the registration is rejected by 5gc because of no "5GMM capability" in Registration Request, but it is mandatory i.e.:

    TRAC[2020-07-30T08:35:46Z]/src/amf/gmm/handler.go:2187 free5gc/src/amf/gmm.HandleSecurityModeComplete() [AMF] Handle MsgTypeRegistrationRequest       AMF=Gmm
    INFO[2020-07-30T08:35:46Z]/src/amf/gmm/handler.go:528 free5gc/src/amf/gmm.HandleRegistrationRequest() [AMF] Handle Registration Request             AMF=Gmm
    DEBU[2020-07-30T08:35:46Z]/src/amf/gmm/handler.go:549 free5gc/src/amf/gmm.HandleRegistrationRequest() RegistrationType: Initial Registration        AMF=Gmm
    DEBU[2020-07-30T08:35:46Z]/src/amf/gmm/handler.go:573 free5gc/src/amf/gmm.HandleRegistrationRequest() SUCI: suci-0-208-93-0000-0-0-0000000001       AMF=Gmm
    INFO[2020-07-30T08:35:46Z]/src/amf/gmm/message/send.go:151 free5gc/src/amf/gmm/message.SendRegistrationReject() [NAS] Send Registration Reject                AMF=Gmm
    INFO[2020-07-30T08:35:46Z]/src/amf/ngap/message/send.go:138 free5gc/src/amf/ngap/message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
    DEBU[2020-07-30T08:35:46Z]/src/amf/ngap/message/send.go:32 free5gc/src/amf/ngap/message.SendToRan() [NGAP] Send To Ran [IP: 127.0.0.1/10.10.0.21:52827]  AMF=NGAP
    ERRO[2020-07-30T08:35:46Z]/src/amf/nas/handler.go:42 free5gc/src/amf/nas.HandleNAS() Handle NAS Error: Capability5GMM is nil       AMF=NGAP

The app.log is also attached.
[app.log](https://github.com/aligungr/ue-ran-sim/files/5000086/app.log)

**Comment by aligungr** [comment]
Hi

Yes you are correct, apparently it is mandatory if the registration request is an initial registration.

I should fix the issue. Relevant three capalities are not supported yet, so the MM capality IE with all zeros should be included in the message.

PRs are appreciated if you can since I have no access to my computer right now :D

**Comment by s5uishida** [comment]
@tim-ywliu 

I have also reached the same point, so I will tell you for reference.
The settings of **free5GC** and **ue-ran-sim** are as follows.

**1) free5GC**
I am using the default settings and changed the log level of `free5GC.conf` to `trace`.
Then, using the webconsole tool, I registerd the following UE information.

- PLMN ID: `20893` <-- default
- SUPI (IMSI): `208930000000003` <-- default
- Authentication Method: `5G_AKA` <-- default
- K: `8baf473f2f8fd09487cccbd7097c6862` <-- default
- Operator Code Type: `OP` <-- I changed from default `OPc` to `OP` according to the format of `ue_i2i.yaml` of ue-ran-sim.
- Operator Code Value: `8e27b6af0e692e750f32667a3b14605d` <-- default

**2) ue-ran-sim**
I built the latest version (with `ALWAYS_LONG_MNC = false`) and changed the configuration files as follows.

a) `gnb.yaml`
```
--- gnb.yaml.orig       2020-07-31 05:00:54.299996743 +0000
+++ gnb.yaml    2020-07-28 03:20:11.221639316 +0000
@@ -1,34 +1,34 @@
 gnbId: 1
 
 gnbPlmn:
-  mcc: 1
-  mnc: 1
+  mcc: 208
+  mnc: 93
 
 amfConfigs:
   - guami:
-      mcc: 1
-      mnc: 1
+      mcc: 208
+      mnc: 93
       amfRegionId:
         hex: '2a'
       amfSetId:
         hex: '5580'
       amfPointer:
         hex: 'a8'
-    host: 10.154.14.19
-    port: 38421
+    host: 127.0.0.1
+    port: 38412
     isMocked: false
     mockingFile: mockedAmf.yaml
 
 supportedTAs:
   - tac:
-      hex: '000075'
+      hex: '000001'
     broadcastPlmns:
       - plmn:
-          mcc: 1
-          mnc: 1
+          mcc: 208
+          mnc: 93
         taiSliceSupportNssais:
           - sst:
               value: 1
-#            sd:
-#              value:
-#                hex: '09afaf'
\ No newline at end of file
+            sd:
+              value:
+                hex: '010203'
```
b) `ue_i2i.yaml`
I set the information of the UE registered in free5GC.
```
--- ue_i2i.yaml.orig    2020-07-31 05:00:54.299996743 +0000
+++ ue_i2i.yaml 2020-07-31 05:12:19.516076669 +0000
@@ -1,28 +1,28 @@
-snn: '5G:mnc001.mcc001.3gppnetwork.org'
-key: '465b5ce8b199b49faa5f0a2ee238a001'
-op: 'cdc202d5123e20f62b6d676ac72cb318'
+snn: '5G:mnc093.mcc208.3gppnetwork.org'
+key: '8baf473f2f8fd09487cccbd7097c6862'
+op: '8e27b6af0e692e750f32667a3b14605d'
 amf: '8000'
 imei: '356938035643809'
-supi: 'imsi-001001000000001'
+supi: 'imsi-208930000000003'
 
 smsOverNasSupported: true
 
 requestedNssai:
   - sst:
       value: 1
-#    sd:
-#      hex: 09afaf
+    sd:
+      hex: 010203
 
 userLocationInformationNr:
   nrCgi:
     plmn:
-      mcc: 1
-      mnc: 1
+      mcc: 208
+      mnc: 93
     nrCellIdentity:
       hex: '01b2c3d4e0'
   tai:
-    mcc: 1
-    mnc: 1
-    tac: '000075'
+    mcc: 208
+    mnc: 93
+    tac: '000001'
   timeStamp:
-    hex: 5b5fa680
\ No newline at end of file
+    hex: 5b5fa680
```

**Comment by s5uishida** [comment]
FYI.

As you may know, I think that [MongoDB Compass](https://www.mongodb.com/products/compass) is a very useful tool for checking the operation of free5GC.

**Comment by s5uishida** [comment]
FYI.

As you may know, there are some test data in **3GPP TS 35.208 "4.3 Test Sets"**.

**Comment by aligungr** [comment]
@tim-ywliu Now 5GMM Capability IE is included in the registration request, the issue should be fixed now.

**Comment by s5uishida** [comment]
I will also report the result briefly.

When executing "initial-registration", the following error was output.

Could you know what is happend?
```
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
New association setup with 5 outbound streams, and 3 inbound streams.
initial-registration
Event pushed.
Type event:
java.lang.NullPointerException
        at tr.havelsan.ueransim.nas.impl.ies.IE5gMmCapability.encodeIE4(IE5gMmCapability.java:67)
        at tr.havelsan.ueransim.nas.NasEncoder.ie2346(NasEncoder.java:96)
        at tr.havelsan.ueransim.nas.NasEncoder.ie2346(NasEncoder.java:114)
        at tr.havelsan.ueransim.nas.core.messages.NasMessage.encodeViaBuilder(NasMessage.java:270)
        at tr.havelsan.ueransim.nas.core.messages.PlainMmMessage.encodeMessage(PlainMmMessage.java:59)
        at tr.havelsan.ueransim.nas.NasEncoder.nasPdu(NasEncoder.java:43)
        at tr.havelsan.ueransim.api.gnb.GnbNasTransport.receiveUplinkNasTransport(GnbNasTransport.java:69)
        at tr.havelsan.ueransim.api.gnb.GNodeB.cycle(GNodeB.java:180)
        at tr.havelsan.ueransim.core.threads.NodeLooperThread.run(NodeLooperThread.java:50)
```
When executing "periodic-registration", ue-ran-sim output the following log and free5GC was panic.
```
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
New association setup with 5 outbound streams, and 3 inbound streams.
periodic-registration
Event pushed.
Type event:
The association has been shutdown.
```

**Comment by aligungr** [comment]
@s5uishida I fixed this issue just now, can you retry?

**Comment by s5uishida** [comment]
free5GC outputs the following log and seems to have succeeded!
Thank you very much!!
```
INFO[2020-08-03T08:21:08Z]/src/amf/gmm/handler.go:2137 free5gc/src/amf/gmm.HandleRegistrationComplete() [AMF] Handle Registration Complete            AMF=Gmm
```
[app_initReg.log](https://github.com/aligungr/ue-ran-sim/files/5014723/app_initReg.log)

However, "periodic-registration" stopped as before.

**Comment by s5uishida** [comment]
I attached the log when "periodic-registration" failed.
[app_perReg.log](https://github.com/aligungr/ue-ran-sim/files/5014767/app_perReg.log)

**Comment by aligungr** [comment]
Actually, periodic registration is performed after initial registration completed and N2 signalling released.

Usually periodic registration should not be triggered manually because UE automatically triggers periodic registration on the expire of T3512. You can watch the T3512 timer in app.log file.

Therefore, even if you want to start periodic registration manually, make sure that you run it after initial registration completed.

**Comment by s5uishida** [comment]
OK.

As a result of continuing "initial-registration" and "periodic-registration", it seems to have succeeded.
I attached [app_init_and_per_Re.log](https://github.com/aligungr/ue-ran-sim/files/5014907/app_init_and_per_Re.log).

And in the latter ("periodic-registration" phase), the following error (2 lines) was output to free5GC.
```
INFO[2020-08-03T08:53:47Z]/src/amf/ngap/handler.go:180 free5gc/src/amf/ngap.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
INFO[2020-08-03T08:53:47Z]/src/amf/gmm/handler.go:528 free5gc/src/amf/gmm.HandleRegistrationRequest() [AMF] Handle Registration Request             AMF=Gmm
INFO[2020-08-03T08:53:47Z]/src/amf/gmm/handler.go:970 free5gc/src/amf/gmm.HandleMobilityAndPeriodicRegistrationUpdating() [AMF] Handle MobilityAndPeriodicRegistrationUpdating  AMF=Gmm
INFO[2020-08-03T08:53:47Z] Request received - NSSelectionGet             NSSF=nsselection
[GIN] 2020/08/03 - 08:53:47 | 200 |     138.131μs |       127.0.0.1 | GET      /nnssf-nsselection/v1/network-slice-information?nf-id=1db7cd3c-dfda-45d6-9557-209263e60acc&nf-type=AMF&slice-info-request-for-registration=%7B%22subscribedNssai%22%3A%5B%7B%22subscribedSnssai%22%3A%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D%2C%22defaultIndication%22%3Atrue%7D%2C%7B%22subscribedSnssai%22%3A%7B%22sst%22%3A1%2C%22sd%22%3A%22112233%22%7D%2C%22defaultIndication%22%3Atrue%7D%2C%7B%22subscribedSnssai%22%3A%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D%7D%2C%7B%22subscribedSnssai%22%3A%7B%22sst%22%3A1%2C%22sd%22%3A%22112233%22%7D%7D%5D%2C%22requestedNssai%22%3A%5B%7B%22sst%22%3A1%2C%22sd%22%3A%22004227%22%7D%5D%7D
INFO[2020-08-03T08:53:47Z]/src/amf/producer/ue_context.go:407 free5gc/src/amf/producer.HandleRegistrationStatusUpdateRequest() Handle Registration Status Update Request     AMF=Comm
[GIN] 2020/08/03 - 08:53:47 | 200 |     256.462μs |       127.0.0.1 | POST     /namf-comm/v1/ue-contexts/5g-guti-20893cafe0000000001/transfer-update
2020/08/03 08:53:47 map[$and:[map[nfType:AMF] map[$or:[map[allowedNfTypes:AMF] map[allowedNfTypes:map[$exists:false]]]]]]
[GIN] 2020/08/03 - 08:53:47 | 200 |     976.015μs |       127.0.0.1 | GET      /nnrf-disc/v1/nf-instances?requester-nf-type=AMF&target-nf-type=AMF
ERRO[2020-08-03T08:53:47Z]/src/amf/producer/callback/n1n2message.go:115 free5gc/src/amf/producer/callback.SendN1MessageNotifyAtAMFReAllocation() unsupported scheme[]                          AMF=HTTP
INFO[2020-08-03T08:53:47Z]/src/amf/ngap/message/send.go:138 free5gc/src/amf/ngap/message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
INFO[2020-08-03T08:53:47Z]/src/amf/ngap/handler.go:180 free5gc/src/amf/ngap.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
ERRO[2020-08-03T08:53:47Z]/src/amf/gmm/sm.go:66 free5gc/src/amf/gmm.register_event_3gpp() Unknown GmmMessage[67]                        AMF=Gmm
```

**Comment by aligungr** [comment]
@s5uishida I am not sure but, related errors may be core network related issue.

**Comment by aligungr** [comment]
@s5uishida configuration changes for free5gc is no longer required.

You can now use `selected-profile: 'free5gc'` at `config/root.yaml`

Could you verify if it works with latest clean build of ueransim?

**Comment by s5uishida** [comment]
It worked fine!

Thank you very much!!

[app.log](https://github.com/aligungr/UERANSIM/files/5021634/app.log)
