### ISSUE TITLE
Question Regarding RRC Messages

### ISSUE THREAD

**Issue by PsArzzz** [aligungr/UERANSIM#735]
Hello @aligungr,

I’ve noticed that some RRC messages do not include an identity (such as ue-identity). How can I determine the target user for these messages?

Without knowing the specific user for a message, I find it challenging to use the user-key mapping table I’ve established, as I wouldn’t know which user’s key to use for decryption. 

For NAS messages, I bind specific keys using the NGAP-ID, allowing me to determine which key to use based on the NGAP-ID of each message. However, I’m at a loss when it comes to RRC messages.

Any help or suggestions would be greatly appreciated!

**Comment by aligungr** [comment]
Hello,

RRC messages are carried with RLS (Radio Link Simulation) layer which is developed by me.

RLS layer tracks the unique identifier of the connection.

I think you might use the ID stored in RLS layer instead of RRC.

Regards.

**Comment by PsArzzz** [comment]
Thanks for the clarification! I appreciate it.
