### ISSUE TITLE
How to Capture More RRC Messages in Open5GS and UERANSIM

### ISSUE THREAD

**Issue by PsArzzz** [aligungr/UERANSIM#736]
Hello @aligungr,

I am currently simulating a 5G network using Open5GS and UERANSIM, both running on an Ubuntu 22.04 virtual machine. I have successfully set up the environment and installed the necessary RLS plugins. While capturing RRC messages, I have only been able to retrieve the following types: MIB, SIB1, RRC Setup Request, RRC Setup, RRC Setup Complete, and Information Transfer.

I am looking for guidance on how to capture additional RRC messages, such as Security Mode Command (not NAS messages), UE Information Request, RRC Reconfiguration, and any others that might be relevant.

Any help or suggestions would be greatly appreciated!

**Comment by aligungr** [comment]
Hello

Indeed, there isn't a real implementation for RRC layer. Only a few messages are supported with a minimal subset of fields.
So, you may not find some other RRC messages.

Regards.

**Comment by PsArzzz** [comment]
Thanks for the clarification! I appreciate it.
