### ISSUE TITLE
About logger and the package hierarchy of UERANSIM/*

### ISSUE THREAD

**Issue by s5uishida** [aligungr/UERANSIM#82]
If you don't mind, please let me know.

1. Could you have any plan to use SLF4J for logger?

1. What do you think about changing the package hierarchy of `UERANSIM/ueransim` as follows:
**tr.havelsan.ueransim --> tr.havelsan.ueransim.app**

Here, the jar is divided into the following bundles and run.

- **`ueransim_1.0.8.jar`**
  This target is `UERANSIM/*` except for `UERANSIM/ueransim`. It contains two shared libraries (lib*.so).

- **`ueransim-app_1.0.8.jar`**
  `UERANSIM/ueransim`

(In addition, `ueransim-activator_1.0.8.jar` (OSGi activator))

The bundles used together are as follows.
- bcpkix-jdk15on-1.66.jar
- bcprov-jdk15on-1.66.jar
- classgraph-4.8.87.jar
- gson-2.8.6.jar
- kotlin-osgi-bundle-1.3.72.jar
- milenage-osgi_1.0.0.jar <-- I made compatible with OSGi.
- org.everit.osgi.bundles.org.json-1.0.0-v20140107.jar
- snakeyaml-1.26.jar
- felix.jar (Apache Felix v6.0.3)

**Comment by aligungr** [comment]
@s5uishida Thanks for the suggestions.

Yes I was planning to use SLF4J, log4j etc in the future. There are many things to do, but we have not much time to complete these goals. If you are a volunteer to make this improvement I would be glad :smile:, otherwise it is not in priorities for now.

Also, I agree with you. it is better to change `tr.havelsan.ueransim` to `tr.havelsan.ueransim.app` (I was planning to change this also)

I'm going to create two separate issues for your two suggestions above. I'll do the package name refactoring, but for logging improvement community helps are needed, since I have no time for it.

--
On the other hand, If I understand you correctly, OSGi is kind of jar packaging tool, but we are currently using maven-shade-plugin for that purpose. It generates only single jar file with all necessary dependencies and shared libraries are included. So if you think OSGİ has some other advantages over maven-shade-plugin please let me now.

**Comment by s5uishida** [comment]
Thank you for your reply.

I think SLF4J is convenient because selecting the implementation of logging in the configuration file.
I'll take a look at your code for a moment.

The `UERANSIM/userransim` package is probably for apps, so it seemed better to separate it from the 3GPP library package.

As an aside, I use OSGi because `MANIFEST.MF` can specify the package's dependency (Import-Package/Export-Package) together with the version. (I'm using the Eclipse Plugin Project)
```
Import-Package: com.google.gson;version="[2.8.6,3.0.0)",
 com.sun.nio.sctp,
...
Export-Package: tr.havelsan.ueransim.app;version="1.0.8",
...
```
I have used some features of OSGi before, but now I mainly use only the above features.

I am using Apache Felix for OSGi framework and the directory structure is as follows. I'm making the code a little change. It is assumed that the directory and bundle for logger will be added to this.
```
ueransim-felix/
  |
  |-- bin/
  |     |
  |     |--- felix.jar
  |     |--- ueransim-start.sh
  |
  |--- bundle/
  |     |
  |     |--- bcpkix-jdk15on-1.66.jar
  |     |--- bcprov-jdk15on-1.66.jar
  |     |--- classgraph-4.8.87.jar
  |     |--- gson-2.8.6.jar
  |     |--- kotlin-osgi-bundle-1.3.72.jar
  |     |--- milenage-osgi_1.0.0.jar
  |     |--- org.everit.osgi.bundles.org.json-1.0.0-v20140107.jar
  |     |--- snakeyaml-1.26.jar
  |     |--- ueransim_1.0.8.jar
  |     |--- ueransim-activator_1.0.8.jar
  |     |--- ueransim-app_1.0.8.jar
  |
  |--- conf/
  |     |
  |     |--- config.properties <-- for felix
  |     |--- custom/
  |     |     |...
  |     |--- free5gc/
  |     |     |...
  |     |--- havelsan/
  |     |     |...
  |     |--- root.yaml
  |     |--- system.properties <-- for felix
  |
  |--- felix-cache/
```

**Comment by aligungr** [comment]
@s5uishida Thanks for your suggestions. I'll make the package name refactoring. However, I think it is not a right time to migrate the app to SLF4J and OSGi, but maybe in the future, thanks.

**Comment by s5uishida** [comment]
Thanks.

I'm looking forward to logger support.

Please do not mind about OSGi. As for myself, I just wanted to handle the bundle dependencies strictly.

**Comment by s5uishida** [comment]
> I'll take a look at your code for a moment.

Since I supported SLF4J & Logback in the trial, the sources are attached. I have done it without changing the original sources and log format as much as possible. I would be glad if it could be a little helpful for your reference.

- [ueransim-src.zip](https://github.com/aligungr/UERANSIM/files/5057452/ueransim-src.zip)
- [ueransim-app-src.zip](https://github.com/aligungr/UERANSIM/files/5057459/ueransim-app-src.zip)

Among them, the changed classes are as follows.

- ueransim-src.zip
```
tr/havelsan/ueransim/utils/
- Console.java
- Logging.java
```
- ueransim-app-src.zip
```
tr/havelsan/ueransim/app/
- AppConfig.java
- Program.java
```
Also, here is a set of packages running on Apache Felix.
[ueransim-felix.zip](https://github.com/aligungr/UERANSIM/files/5057473/ueransim-felix.zip)

The` logback.xml` is as follows. Also, I have included `app.0.log` for reference.
```
config/logback.xml
logs/app.0.log
```
The log files are set to rotate from `app.0.log` up to 10 files of `app.9.log`. The maximum size of one log file is set to 100KB.

It could be run as follows.
```
$ cd ueransim-felix/bin
$ sh ueransim-start.sh
...
```
Please use `kill -9` to terminate the process.

**Comment by aligungr** [comment]
@s5uishida Thanks for the work, I will check it soon.

**Comment by s5uishida** [comment]
Thanks.

The original source is the following version. (2020/08/06)
```
commit:f86a5689b87d6fcebc638c40d9edd590e8ba0e68
```

**Comment by s5uishida** [comment]
Just a bit, I tried LoadTest. (successed)

The environment and conditions are as follows.

- VM on VirtualBox (on Ubuntu 18.04)
  - Ubuntu 18.04 (5.0.0-23-generic)
  - 1 Core, 8GB Mem
- free5GC & UERANSIM on the same VM (Both are the latest on 2020/08/21)
  - imsi-208930000000003 --> imsi-208930000000052 (50 entries)

The contents of [logs.zip](https://github.com/aligungr/UERANSIM/files/5107165/logs.zip) for **`initial-registration`** are as follows. (SLF4J & Logback)
```
logs/
  |
  |--- app.0.log     <newest>
  |--- app.1.log        |
  |--- app.2.log        |
  |--- app.3.log        |
  |--- app.4.log        V
  |--- app.5.log     <oldest>
  |--- loadtest.0.log
```

**Comment by aligungr** [comment]
@s5uishida  I had been said that i will check "soon", but still could not check. I am sorry :smile:

Currently working on some deep changes on running of the simulator. Also doing some refactoring.

I just wanted to let you know.

**Comment by s5uishida** [comment]
Thank you for your reply.

Please do not mind about the logger. Please progress the developing this excellent program at your own pace. The UE/RAN simulators developed in Java are very interesting.

Also, thank you very much for the package hierarchy.
