### ISSUE TITLE
cp: cannot stat ‘libcrypto-native.so’: No such file or directory

### ISSUE THREAD

**Issue by 5gsimuser** [aligungr/UERANSIM#98]
Hi ,
I am getting this error while building the 5gsimulator , could you please check the error log.
thank you very much for your time.

[5g-sim-errorlog.txt](https://github.com/aligungr/UERANSIM/files/5096807/5g-sim-errorlog.txt)

I am using open-jdk11.
gcc version 4.8.5
.

**Comment by aligungr** [comment]
Hi @5gsimuser 

Make sure that you have the latest version of gcc/g++. Indeed 4.8.5 is an old version.

```
sudo apt update
sudo apt upgrade
sudo apt install g++
```

After that, you can try to rebuild the simulator with `./build.sh.` More details are written on the README file.

**Comment by 5gsimuser** [comment]
As you said i have update the gcc/g++ version. now i am trying to ./build.sh getting error at initial stage of building.

[buildErrorlog.txt](https://github.com/aligungr/UERANSIM/files/5103062/buildErrorlog.txt)


[dev@robi-app UERANSIM-master]$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/dev/apache-maven-3.6.3
Java version: 11.0.8, vendor: Oracle Corporation, runtime: /home/dev/5gsim/jdk-11.0.8
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-147.el8.x86_64", arch: "amd64", family: "unix"

**Comment by 5gsimuser** [comment]
Thank you successfully build but while run getting this bellow error.


[dev@robi-app UERANSIM-master]$
[dev@robi-app UERANSIM-master]$
[dev@robi-app UERANSIM-master]$ ./run.sh
INFO: Selected profile: "free5gc"
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration",
  "pdu-session-establishment"
]
Enter event to execute:
java.lang.RuntimeException: java.net.SocketException: Protocol not supported
        at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:52)
Caused by: java.net.SocketException: Protocol not supported
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket0(Native Method)
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket(SctpNet.java:85)
        at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.<init>(SctpChannelImpl.java:137)
        at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:170)
        at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:225)
        at tr.havelsan.ueransim.sctp.SctpClient.start(SctpClient.java:63)
        at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:49)
[dev@robi-app UERANSIM-master]$

**Comment by aligungr** [comment]
@5gsimuser My guess is the following. Are you running the simulator on Linux VM contained in Windows? Windows does not support SCTP protokol, therefore physical Linux machine is required. Otherwise SCTP won't work.

**Comment by 5gsimuser** [comment]
I am using physical Linux machine which accessing remote through putty.

[dev@robi-app UERANSIM-master]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

**Comment by aligungr** [comment]
OK, could you check the linux kernel version with `uname -r`

**Comment by 5gsimuser** [comment]
[dev@robi-app UERANSIM-master]$ uname -r
4.18.0-147.el8.x86_64

**Comment by aligungr** [comment]
I think it is Red Hat related error. I am only sure that Ubuntu 16.04 and later should work. However for other versions and distributions it may not work.

**Comment by 5gsimuser** [comment]
Okay, then can i try it in ubuntu 16.04 and later which is intalled in vmware in windows machin.

**Comment by aligungr** [comment]
Unfortunately no. Any Linux VM contained in Windows also cannot handle SCTP.

**Comment by 5gsimuser** [comment]
oho,! Is any solution to handle this dependency in linux keranl 4.18.0-147 .  if yes please guide me.
I have no option to go for dedicated Ubuntu machine.

**Comment by aligungr** [comment]
This link may be helpful
https://access.redhat.com/solutions/3682041
